### ISSUE TITLE
[BUG] Logos of open source community

### ISSUE THREAD

**Issue by himanshu1221** [layer5io/layer5#3954] opened 2023-03-13 05:38 UTC
### Description

Logo of communities such as CNCF , open application model are not visible

### Expected Behavior

they should look appropriate in the frame

### Screenshots

![Screenshot from 2023-03-13 11-05-37](https://user-images.githubusercontent.com/32031706/224616731-ce4a91d9-e1f1-4258-9329-7ff41f190e00.png)

### Environment:
- Host OS: UBUNTU
- Browser: CHROME 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by sambhavgupta0705** [comment] 2023-03-13 08:58
Hi @himanshu1221 Can I work on this issue?

**Comment by himanshu1221** [comment] 2023-03-13 09:00
> Hi @himanshu1221 I would like to work on this issue.Can you please assign it to me .

hey @sambhavgupta0705 I am currently working on this issue you can find  another issues

**Comment by money8203** [comment] 2023-03-14 18:04
@Chadha93 @Nikhil-Ladha any comments on this one ?

**Comment by Nikhil-Ladha** [comment] 2023-03-14 18:29
This is by design and not a BUG. Hence, closing it out.

**Closed by Nikhil-Ladha** 2023-03-14 18:29 UTC
Labels: kind/bug
