### ISSUE TITLE
[Performance] Layer5 logo not cached?

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2606] opened 2022-02-14 22:22 UTC
**Current Behavior**
It seems that the Layer5 logo is (re)downloaded with each page visit. See the behavior in the attached recording.

https://user-images.githubusercontent.com/7570704/153956445-363bf495-d2ac-4409-ba16-d5d00cc31a12.mov

**Desired Situation**
This logo and other image files should be cached. 

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment] 2022-02-14 22:23
@Nikhil-Ladha @debo19 @kayceeDev does this behavior seem correct?

**Comment by kayceeDev** [comment] 2022-02-14 23:23
The blur effect is coming from the Gatsby config due the way the Gatsby static image rendering works. Instead of loading all the image at once, it blurs the image as a way to optimise the load time. It's more like loading the image data in chunks till it's fully loaded rather than wait for the image to load up at once. So it is not redownloaded. That's the expected behaviour with Gatsby static image plugin.

**Comment by leecalcote** [comment] 2022-02-14 23:26
@kayceeDev, thanks. That makes sense. Let's investigate caching of this and other static images, so that they don't need to be downloaded on (soft) refresh.

**Comment by kayceeDev** [comment] 2022-02-14 23:29
Alright. Will look into it.🤗

**Comment by Nikhil-Ladha** [comment] 2022-03-04 13:48
> @kayceeDev, thanks. That makes sense. Let's investigate caching of this and other static images, so that they don't need to be downloaded on (soft) refresh.

It doesn't re-downloads but just loads with the effect of a blur, while the rest of the page continues to be loaded/built by the browser.
The best fix for this is to avoid the `StaticImage` component on the logo.

**Comment by kayceeDev** [comment] 2022-03-04 13:54
> > @kayceeDev, thanks. That makes sense. Let's investigate caching of this and other static images, so that they don't need to be downloaded on (soft) refresh.
> 
> It doesn't re-downloads but just loads with the effect of a blur, while the rest of the page continues to be loaded/built by the browser. The best fix for this is to avoid the `StaticImage` component on the logo.

I agree with you @Nikhil-Ladha. We can remove the `StaticImage` component to restore the original logo behaviour.

**Comment by Nikhil-Ladha** [comment] 2022-03-04 14:11
Let's have this under the `good-first-issue` list.

**Comment by a-muk** [comment] 2022-03-04 14:16
Can I try to work on this issue?

**Comment by Abhijay007** [comment] 2022-03-04 14:22
> Can I try to work on this issue?

sure @a-muk go ahead :)

**Comment by Ash-KODES** [comment] 2022-03-13 20:10
Since,no PR is made till now,Can I work on this?
#openforce2022

**Comment by debo19** [comment] 2022-03-13 21:08
@a-muk any updates? @Ash-KODES can help you out here :)

**Comment by a-muk** [comment] 2022-03-14 02:28
@debo19 wld be great if I could get some help.

**Comment by Nikhil-Ladha** [comment] 2022-03-19 12:34
> @debo19 wld be great if I could get some help.

Where are you stuck?

**Comment by Ash-KODES** [comment] 2022-03-19 13:57
> > @debo19 wld be great if I could get some help.
> 
> Where are you stuck?

Actually i am not able to locate the required code since i am new the codebase

**Comment by a-muk** [comment] 2022-03-19 18:43
No problem @Ash-KODES . @Nikhil-Ladha I kinda figured out the problem, even changed the code but am facing problems while setting up the project - as in while seeing the output. I also wrote about the problem on the slack channel where I got help from many people. Give me sometime to try all those out. Is that fine?

**Comment by Nikhil-Ladha** [comment] 2022-03-19 18:53
> No problem @Ash-KODES . @Nikhil-Ladha I kinda figured out the problem, even changed the code but am facing problems while setting up the project - as in while seeing the output. I also wrote about the problem on the slack channel where I got help from many people. Give me sometime to try all those out. Is that fine?

Sure, just don't take too long :)

**Comment by a-muk** [comment] 2022-03-21 14:48
@Nikhil-Ladha I made the changes. Do have a look at it!

**Comment by kayceeDev** [comment] 2022-03-21 15:13
> @Nikhil-Ladha I made a PR after fixing this issue. Do have a look at it!

Provide a link to to your PR. Well done! :clap: @a-muk

**Comment by a-muk** [comment] 2022-03-21 15:14
https://github.com/layer5io/layer5/pull/2674

**Closed** 2022-03-23 07:58 UTC
Labels: good first issue, kind/chore, first-timers-only, openforce
