### ISSUE TITLE
Heading is not bold in brand page

### ISSUE THREAD

**Issue by amitamrutiya** [layer5io/layer5#5788] opened 2024-08-05 14:39 UTC
### Description
Link: [Company brand page](https://layer5.io/company/brand)
Logos and colors headings are not bold in this particular section.

### Expected Behavior
It should be same as other heading

### Screenshots
![image](https://github.com/user-attachments/assets/502b3acd-99bf-47eb-8286-91076ce1b035)

### Environment:
- Host OS: Linux
- Browser: Firefox

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by amitamrutiya** [comment] 2024-08-05 14:39
If you find this issue valid then I want to work on this.

**Comment by Ashparshp** [comment] 2024-08-13 03:58
@amitamrutiya, The issue is that some headings are `<h3>` while others are `<h2>`. Let's decide which one to use to maintain consistency.

**Comment by amitamrutiya** [comment] 2024-08-13 04:49
Okay

**Comment by Ashparshp** [comment] 2024-08-13 07:12
@amitamrutiya, @hargunkaur286 Any suggestions?

**Comment by amitamrutiya** [comment] 2024-08-13 08:17
I think we should use the `h2` tag for section headings and the `h3` tag for logo and color titles. The current setup in the MeshSync section looks good to me. It's also a best practice to avoid using multiple `h1` tags on a single page.

![image](https://github.com/user-attachments/assets/ef2de129-1e42-4bf7-b863-289875b452b5)

Since @H-A-R-S-H-K has already made a PR, please assign this issue to him.

**Comment by Ashparshp** [comment] 2024-08-26 09:01
Completed.

**Comment by vishalvivekm** [comment] 2024-08-31 22:41
@Ashparshp how is this issue completed when the PR that fixes it hasn't been merged yet ?
https://github.com/layer5io/layer5/pull/5804

**Comment by Ashparshp** [comment] 2024-08-31 23:21
My bad @vishalvivekm.

**Comment by Ashparshp** [comment] 2024-08-31 23:22
Now, as u merged it. We can close now.

**Comment by vishalvivekm** [comment] 2024-08-31 23:23
> Now, as u merged it. We can close now.

:heavy_check_mark:

**Closed by Ashparshp** 2024-08-31 23:22 UTC
Labels: kind/bug
