### ISSUE TITLE
Code Quality Improvement: Variable declared but not in use.

### ISSUE THREAD

**Issue by saaagarsingh** [layer5io/layer5#4492] opened 2023-07-06 13:26 UTC
### Description
There are several variables in different-different files that are being declared but not in use.
Eslint shows 7 warning and 1 error related to that.

### Expected Behavior
There should be code cleanup and variables that are not in use should be removed.
For reference I've attached a screenshot through which one can understand the files where one needs to the cleanup.

### Screenshots
![layer5consoleWarnings](https://github.com/layer5io/layer5/assets/85694019/419d1134-7306-4003-a6d7-75d589da599d)

### Environment:
- Host OS: Windows 10
- Browser:Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by tanbirali** [comment] 2023-07-06 17:48
Can I work on this issue?

**Comment by RakshitKumar04** [comment] 2023-07-06 19:42
Hey, @saaagarsingh I have already started working on this issue, could you please assign this issue to me.

**Comment by RakshitKumar04** [comment] 2023-07-06 20:55
Hey, @saaagarsingh please take a look.

**Comment by saaagarsingh** [comment] 2023-07-07 00:27
@RakshitKumar04 I don't have the rights to assign anyone. @leecalcote may help you on this.

**Comment by RakshitKumar04** [comment] 2023-07-07 03:45
Hey, @leecalcote please assign the issue to me, and review my PR.

**Comment by Saksham294** [comment] 2023-07-08 20:47
Guys please don't create PRs until an issue has been assigned to you.

**Comment by leecalcote** [comment] 2023-07-09 01:06
> Guys please don't create PRs until an issue has been assigned to you.

Sound counsel. Get us wrong, we certainly appreciate the enthusiasm, however, confirming assignment, first will avoid heartache in the form of:

1. Issue not qualified: effort put into an invalid issue.
2. Contributor conflict: a bit of stepping on toes and not so kindly pushing others out of the way. Certainly don't want the project to move slowly, but a little bit of kindness goes a long way.
3. Maintainer cycles spent clarifying and assuaging ruffled feathers (hurt feelings).

Is the issue described above valid? _Yes_
Do we want this issue fixed? _Yes_
Do we generally assign issues in chronological order of contributor request? _Yes_
Are there exceptions to that rule? _Yes_
If yes, when? _When the requesting contributor is 1) unqualified, or 2) unavailable or incapable of delivering in a timely fashion, or 3) missing too much context and whereas another contributor already has that context, or 4) when a requesting contributor already has one or more other open assignments.

@Saksham294, will you do me a favor and place this info into an FAQ and/or section of the Community Handbook?

@RakshitKumar04, since you have an open PR and the issue is valid, we'll move forth with your assignment. Take note of @Saksham294's counsel for future reference, if you would, please. My counsel is to take a moment to soften your phrasing; too apply a touch of kindness in your interactions.

**Comment by leecalcote** [comment] 2023-07-09 01:11
@Saksham294 I'll let you perform issue triage and PR review. Thanks for helping steward us. 👍

**Comment by RakshitKumar04** [comment] 2023-07-09 05:55
@leecalcote @Saksham294 I am really sorry, that I opened a PR without getting it assigned to me. It was just that I started to get the code base and was really eager to contribute.

**Comment by leecalcote** [comment] 2023-07-09 16:54
@RakshitKumar04, no sweat. I completely understand. We would much rather that this happen than have issues go stale. Keep on 🏃‍♂️

**Comment by leecalcote** [comment] 2023-07-09 16:54
> @Saksham294 I'll let you perform issue triage and PR review. Thanks for helping steward us. 👍

@Saksham294 I'll go ahead and triage...

**Closed** 2023-07-09 16:55 UTC
Labels: kind/bug
