### ISSUE TITLE
Use white needle version of logo in dark-mode

### ISSUE THREAD

**Issue by vishalvivekm** [layer5io/layer5#4586] opened 2023-07-20 12:28 UTC
### Description

The SMP logo on  [Homepage](https://layer5.io) has black needle.
![Screenshot 2023-07-20 at 7 17 03 AM (1)](https://github.com/layer5io/layer5/assets/126756092/4c7fd32e-443e-452e-88b1-e73fc11f7711)

### Expected Behavior

Let's use the light version of the logo with the white needle for dark mode : <a href="https://github.com/layer5io/layer5/tree/master/src/assets/images/service-mesh-performance/icon/smp-light.svg"> smp-light.svg</a>

**Note**: Both versions of the logo must be present to support both light and dark modes on the site.

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by samyakshah3008** [comment] 2023-07-20 13:05
Hi @Chat-Ritik just to check that have you setup layer5 repo project locally?

**Comment by Chat-Ritik** [comment] 2023-07-20 13:11
Hi @samyakshah3008, I am new to Layer5 community and I am just setting up layer5 repo locally.

**Comment by Ahmadjajja** [comment] 2023-07-20 14:08
Can you assign this task to me?

**Comment by Chat-Ritik** [comment] 2023-07-20 19:20
@vishalvivekm I am working on this issue. It is taking a bit longer as this is my very first issue in terms of contribution to any open source project.

**Comment by vishalvivekm** [comment] 2023-07-21 04:59
@Chat-Ritik 
Please take a look now at the issue #4586's description updated  with the light version of the logo with the white needle that is to be used in dark mode.
// @ducksblock

Note: SVGs are not to be edited.

**Comment by Chat-Ritik** [comment] 2023-07-21 05:05
Yes, I understood. Thanks

**Comment by nakulbh** [comment] 2023-07-21 17:57
Can i also work on this issue 
please assign this to me i have project setup locally

**Comment by Chat-Ritik** [comment] 2023-07-23 17:01
Hello @vishalvivekm , @samyakshah3008 , below I have attached the code of src/sections/Home/Projects-home/index.js file in which have highlighed the changes I made to solve this issue #4586. 

import React, { useContext } from "react";
import { Link } from "gatsby";
import { Container, Row, Col } from "../../../reusecore/Layout";
import SectionTitle from "../../../reusecore/SectionTitle";
import ProjectItemWrapper from "./projectSection.style";
import { StaticImage } from "gatsby-plugin-image";
import Button from "../../../reusecore/Button";
import CatalogLogo from "../../../assets/images/catalog-icon/catalog";
**import { ThemeManagerContext, ThemeManagerProvider, ThemeSetting } from "../../../theme/app/ThemeManager";**

const Projects = () => {
  const projectsIcon = "./images/projects.svg";
  
  **const { isDark, didLoad } = useContext(ThemeManagerContext);**

  **const projectImage2_light = "../../../assets/images/service-mesh-performance/icon/smp-light.svg";
  const projectImage2_dark = "../../../assets/images/app/projects/smp.webp";**
  const projectImage3 = "../../../assets/images/app/projects/meshery-logo-light.webp";
  const projectImage4 = "../../../assets/images/app/projects/nighthawk-logo.webp";
  const meshmapLogo = "../../../assets/images/meshmap/icon-only/meshmap-icon.svg";
  
  **if(!didLoad){
    return null;
  }**

  return (
    <ProjectItemWrapper id="projects">
      <Container>
        <Row>
          <div className="project-title">
            <SectionTitle
              className="section-title"
              leftAlign={true}
              UniWidth="75%"
            >
              <h2>
                Operate cloud native infrastructure <span>with confidence</span>.
              </h2>
            </SectionTitle>
          </div>
        </Row>
        <Row>
          <div className="project__block__wrap">
            <Col sm={12} md={6} lg={3}>
              <Link className="project-card" to="/cloud-native-management/meshmap">
                <div className="project__block__inner">
                  <StaticImage loading="lazy" src={meshmapLogo} alt="MeshMap Logo" width={50} height={80} imgStyle={{ width: "24px", height: "39px" }} />
                  <p>MeshMap</p>
                  <h3>Collaborative GitOps</h3>
                  {/* <h3>Multiplayer Kubernetes by Design</h3> */}
                </div>
              </Link>
            </Col>
            <Col sm={12} md={6} lg={3}>
              <Link className="project-card" to="/cloud-native-management/meshery">
                <div className="project__block__inner">
                  <StaticImage loading="lazy" src={projectImage3} alt="Meshery Logo" width={80} height={80} imgStyle={{ width: "40px", height: "40px" }} />
                  <p>Meshery</p>
                  <h3>Cloud Native Management and Governance</h3>
                </div>
              </Link>
            </Col>
            <Col sm={12} md={6} lg={3}>
              <Link className="project-card" to="/projects/service-mesh-performance">
                <div className="project__block__inner">
                  **<ThemeManagerProvider>
                   {( isDark ) ? (
                     <StaticImage loading="lazy" src={projectImage2_light} alt="Light Mode SMP Logo" width={294} height={120} imgStyle={{ width: "98px", height: "40px" }}/>
                   ) : (
                     <StaticImage loading="lazy" src={projectImage2_dark} alt="Dark Mode SMP Logo" width={294} height={120} imgStyle={{width: "98px", height: "40px"}}/>
                   )}
                  </ThemeManagerProvider>**
                  <p>Cloud Native Performance</p>
                  <h3>Infrastructure Value Measurement</h3>
                </div>
              </Link>
            </Col>............................................
                     .............................................
                    ..............................................

Here, didLoad ensures that the theme is already detected. In case the theme is not detected(when webpage is reloaded), it makes sure that neither version of logo is rendered, so I have to return null while loading of page. As soon as theme is deteched(page is loaded), it works fine. 
If I don't make use of  didLoad, the dark version of logo is always rendered(as theme not yet detected) on reloading and when website is initially logged In. 
As per the code provided, the website appears as shown in video attached, it looks unpleasant when reloading. Can you suggest ways I can improve the code and tackle this problem. Thanks for giving your valuable time.      
      
[Screencast from 23-07-23 09:55:56 PM IST.webm](https://github.com/layer5io/layer5/assets/125290059/02805f26-12fc-4995-883c-6652cb72310d)

**Comment by Chat-Ritik** [comment] 2023-07-23 17:28
Hello @vishalvivekm , @samyakshah3008 , below I have attached the some part of code of src/sections/Home/Projects-home/index.js file in which have highlighted the changes I made to solve this issue.

import React, { useContext } from "react";
import { Link } from "gatsby";
import { Container, Row, Col } from "../../../reusecore/Layout";
import SectionTitle from "../../../reusecore/SectionTitle";
import ProjectItemWrapper from "./projectSection.style";
import { StaticImage } from "gatsby-plugin-image";
import Button from "../../../reusecore/Button";
import CatalogLogo from "../../../assets/images/catalog-icon/catalog";
**import { ThemeManagerContext, ThemeManagerProvider, ThemeSetting } from "../../../theme/app/ThemeManager";**

const Projects = () => {
const projectsIcon = "./images/projects.svg";

**const { isDark, didLoad } = useContext(ThemeManagerContext);**

**const projectImage2_light = "../../../assets/images/service-mesh-performance/icon/smp-light.svg";
const projectImage2_dark = "../../../assets/images/app/projects/smp.webp";**
const projectImage3 = "../../../assets/images/app/projects/meshery-logo-light.webp";
const projectImage4 = "../../../assets/images/app/projects/nighthawk-logo.webp";
const meshmapLogo = "../../../assets/images/meshmap/icon-only/meshmap-icon.svg";

**if(!didLoad){
return null;
}**

return (
Operate cloud native infrastructure with confidence.
.....................................................
.....................................................
.....................................................
**{( isDark ) ? (
<StaticImage loading="lazy" src={projectImage2_light} alt="Light Mode SMP Logo" width={294} height={120} imgStyle={{ width: "98px", height: "40px" }}/>
) : (
<StaticImage loading="lazy" src={projectImage2_dark} alt="Dark Mode SMP Logo" width={294} height={120} imgStyle={{width: "98px", height: "40px"}}/>
)}**
Cloud Native Performance
............................................
.............................................
..............................................

Here, didLoad ensures that the theme is already detected. In case the theme is not detected(when webpage is reloaded), it makes sure that neither version of logo is rendered, so I have to return null while loading of page. As soon as theme is deteched(page is loaded), it works fine.
If I don't make use of didLoad, the dark version of logo is always rendered(as theme not yet detected) on reloading and when website is initially logged In.
As per the code provided, the website appears as shown in video attached, it looks unpleasant when reloading. Can you suggest ways I can improve the code and tackle this problem. Thanks for giving your valuable time.

[Screencast from 23-07-23 09:55:56 PM IST.webm](https://github.com/layer5io/layer5/assets/125290059/0da4b70c-c709-416a-8615-263c07a7972d)

**Comment by samyakshah3008** [comment] 2023-07-23 17:35
Please raise a PR @Chat-Ritik

**Comment by Chat-Ritik** [comment] 2023-07-23 17:37
> Please raise a PR @Chat-Ritik

Okay, I'll do it.

**Closed** 2023-07-26 21:15 UTC
Labels: kind/bug, help wanted, good first issue
