### ISSUE TITLE
card overflowing on Service Mesh Interface page

### ISSUE THREAD

**Issue by anshitmishra** [layer5io/layer5#4378] opened 2023-06-14 04:18 UTC
### Description

image card overflowing on the Service Mesh Interface page [https://layer5.io/projects/service-mesh-interface-conformance](https://layer5.io/projects/service-mesh-interface-conformance)
### Expected Behavior

image card should be inside the screen currently its overflowing
### Screenshots
<!
![Screenshot (91)](https://github.com/layer5io/layer5/assets/91340109/00c0168b-ed4e-4586-99c6-7f27a12ebafc)
-- Add screenshots, if applicable, to help explain your problem. -->

### Environment:
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by anshitmishra** [comment] 2023-06-14 04:20
I would like to work on this issue. Please assign me

**Comment by DarrenDsouza7273** [comment] 2023-06-14 11:32
I have assigned the issue to you @anshitmishra you can work on it now,
If you have any doubts or are facing any issues you can put up your issue/query in the discussion Forum : http://discuss.layer5.io/

**Comment by anshitmishra** [comment] 2023-06-14 12:54
@DarrenDsouza7273 thanks

**Comment by saaagarsingh** [comment] 2023-06-15 04:24
Hey @anshitmishra let me know if I could be of any help. Looking for my first contribution to get started.

**Comment by anshitmishra** [comment] 2023-06-15 14:41
Sure @saaagarsingh . meanwhile Do look out for other open issues.

**Comment by saaagarsingh** [comment] 2023-06-17 04:29
Hey @anshitmishra are you still working on this?

**Comment by anshitmishra** [comment] 2023-06-17 07:36
@saaagarsingh Sorry i am currently busy with my other issue you can take this issue

**Comment by DarrenDsouza7273** [comment] 2023-06-17 08:10
@saaagarsingh you can go ahead and work on this issue

**Comment by saaagarsingh** [comment] 2023-06-17 10:30
sure thing. starting to work on it.

**Comment by DarrenDsouza7273** [comment] 2023-06-19 13:07
Hi @saaagarsingh can u please update

**Comment by saaagarsingh** [comment] 2023-06-19 17:42
Hey @DarrenDsouza7273 I was having some work but now I'm free. Just need a help setting up the Project in my local system. I'm getting some errors

**Comment by Shivam-AfA** [comment] 2023-06-20 08:04
@saaagarsingh What erros are you facing?

**Comment by Manish254252** [comment] 2023-06-21 03:47
any update on this

**Comment by saaagarsingh** [comment] 2023-06-21 06:40
Hey @Manish254252 I've done the necessary changes but while commiting it throws error related to eslint. I posted it on discussas well. Do you know how to resolve it?

**Comment by Shivam-AfA** [comment] 2023-06-21 06:46
@saaagarsingh use `npm run lint`

**Comment by saaagarsingh** [comment] 2023-06-21 06:59
Still the same. it shows eslint is not recognised as an internal or external command.

**Comment by saaagarsingh** [comment] 2023-07-07 05:41
@DarrenDsouza7273 please have a look at the PR It has passed all the checks.

**Comment by Nikhil-Ladha** [comment] 2023-07-12 18:38
The card is not overflowing, it is by design. Closing the issue for the same reason, please close out the open PRs.
Sorry for the trouble you all had to go through.

**Closed by Nikhil-Ladha** 2023-07-12 18:38 UTC
Labels: kind/bug

**Comment by saaagarsingh** [comment] 2023-07-13 05:01
@Nikhil-Ladha I think its not by design since the part of the card which contains certain information is not visible to the end user. Please check it once again if you would.

**Comment by Nikhil-Ladha** [comment] 2023-07-13 05:23
> @Nikhil-Ladha I think its not by design since the part of the card which contains certain information is not visible to the end user. Please check it once again if you would.

Yeah, I know.
Secondly, that is an outdated table and kept just for _design_. The actual SMI table is on the landscape page which get updated automatically using a script.
So, yes _it is by design_ 🙂
