### ISSUE TITLE
Projects Page: Most of the services are hidden after width is less than 550px.

### ISSUE THREAD

**Issue by Krishna2323** [layer5io/layer5#3292] opened 2022-10-09 08:30 UTC
#### Description
Projects Page: Most of the services are hidden after width is less than 550px.
![Screenshot 2022-10-09 135740](https://user-images.githubusercontent.com/85894871/194746345-b336f455-ab2b-4d05-9b0a-43c49b72ba6f.png)

#### Expected Behavior
![Screenshot 2022-10-09 135715](https://user-images.githubusercontent.com/85894871/194746362-2b08faa8-bbed-4423-a448-af08a0edb4f7.png)

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by arpitghura** [comment] 2022-10-10 15:19
I would like to work on this issue. Can you please assign it to me?

**Comment by Nikhil-Ladha** [comment] 2022-10-18 09:31
This is by design.
Though an improvement can be done here and that is removing the left, and right margins for that particular section.
That would be around `-5%`.

@arpitghura interested to work on this issue? Do you have your setup complete and have the site running locally?

**Comment by rohanyrane** [comment] 2022-10-22 12:39
Please assign me this issue

**Comment by Nikhil-Ladha** [comment] 2022-10-22 18:28
@rohanyrane sure will do that.
Though, before doing so could you please confirm if you have the setup done and if you are able to run the site locally (probably with a screenshot of a successful build)?

**Comment by rohanyrane** [comment] 2022-10-23 03:47
> @rohanyrane sure will do that. Though, before doing so could you please confirm if you have the setup done and if you are able to run the site locally (probably with a screenshot of a successful build)?
![image](https://user-images.githubusercontent.com/91753741/197372672-acd8ffce-8c10-4ae0-a0cd-ccce51f7575e.png)
@Nikhil-Ladha

**Comment by Nikhil-Ladha** [comment] 2022-10-23 03:55
Cool, go ahead

**Comment by rohanyrane** [comment] 2022-10-23 04:59
@Nikhil-Ladha do you want the expected behavior for every width or for only width>550px ? Because even for width > 550px some of the card's portion is hidden

**Comment by Nikhil-Ladha** [comment] 2022-10-23 16:05
Only from `width < 568px`.
The cut-off is intentional.

**Comment by tinniaru3005** [comment] 2022-12-10 14:03
@Krishna2323 is this issue solved? Otherwise I would like to work on it

**Comment by leecalcote** [comment] 2022-12-10 14:41
Thank you, @tinniaru3005

**Closed** 2022-12-16 10:08 UTC
Labels: kind/bug
