### ISSUE TITLE
[Bug]Non-uniform height when hovered

### ISSUE THREAD

**Issue by Ghat0tkach** [layer5io/layer5#4542] opened 2023-07-14 09:17 UTC
### Description

in the [handbook](https://layer5.io/community/handbook) page , whenever we hover the elements the following disturbance occurs

https://github.com/layer5io/layer5/assets/59855919/3921c9e7-89d1-457e-a810-bfbd543052ca

### Expected Behavior

I have done the following changes to resolve the bug

## Fix 1 : With scale property  

https://github.com/layer5io/layer5/assets/59855919/fe3efe0b-664a-4afb-9652-726be5a5f0db

##  Fix 2 : Without scale property 

https://github.com/layer5io/layer5/assets/59855919/3b2f1c4f-4b60-44e8-a6bd-04fcdb94be84

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Ghat0tkach** [comment] 2023-07-14 09:38
I would like to work on this issue 😅

**Comment by DarrenDsouza7273** [comment] 2023-07-14 15:24
Assigned to you @Ghat0tkach

**Comment by leecalcote** [comment] 2023-07-16 06:12
Caused by this PR https://github.com/layer5io/layer5/pull/4544

**Closed** 2023-07-17 10:42 UTC
Labels: kind/bug
