### ISSUE TITLE
[Learn] Sidebar needs enhancement

### ISSUE THREAD

**Issue by afzal442** [layer5io/layer5#2040] opened 2021-07-29 07:41 UTC
**Current Behavior**

The sidebar looks weird. It is a bit down to see around.
While clicking on subtitles, this takes/navigates you to a different section. e.g. click on subtitle  [Working with Meshery & Consul](https://layer5.io/learn-ng/mastering-meshery-consul)
**Desired Behavior**

- [ ] The sidebar needs to be standardised.
- [ ] When you click on any title bars, this should properly navigate you.

---
**Screenshots / Mockups**

![c2](https://user-images.githubusercontent.com/11625672/127451016-a6b57acb-ed56-4ab6-a67c-62397fe7c32d.JPG)

**Alternatives**

<img width="801" alt="c3" src="https://user-images.githubusercontent.com/11625672/127451570-597b54b4-a6b5-45d4-8ecd-9792351d71f1.png">

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by afzal442** [comment] 2021-07-29 07:44
Hi @sudo-NithishKarthik, what do you think?

**Comment by Nikhil-Ladha** [comment] 2021-07-29 07:51
What's wrong with the navigation, again?

**Comment by Nikhil-Ladha** [comment] 2021-07-29 07:51
Also, the height of the sidebar should match rhe content beside it. But, yes the margin around the title can be reduced a bit.

**Comment by afzal442** [comment] 2021-07-29 07:54
> What's wrong with the navigation, again?

hi @Nikhil-Ladha! sure, can you try clicking on the mentioned subtitle? for example, when you click on that, it navigates you to a different section. Thanks.

**Comment by Nikhil-Ladha** [comment] 2021-07-29 07:55
Hmm, I don't think so 🤔....it works fine for me.

**Comment by Nikhil-Ladha** [comment] 2021-07-29 07:57
The general issue with an `id` navigation in case the page has a navigation bar is that the `element` to which the href is pointed to gets hidden behind the navbar.

**Comment by afzal442** [comment] 2021-07-29 08:05
> Maybe, adding a little padding around it can help, but one needs to experiment that.

Yep I agree. That way we can get rid of this. Also defining classes `mb-5` or `p-3` #bootstrap mark. Just for intuition.

**Comment by sudo-NithishKarthik** [comment] 2021-08-04 04:27
> The sidebar looks weird. It is a bit down to see around

Can you elaborate on it?



> While clicking on subtitles, this takes/navigates you to a different section. e.g. click on subtitle Working with Meshery & Consul

Yes, i see what the issue is here, can you make a pr for it ?

**Comment by afzal442** [comment] 2021-08-04 06:09
Learn-ng | Layer5 - The Service Mesh Company - Watch Video

**Comment by afzal442** [comment] 2021-08-04 06:09
https://www.loom.com/share/1b413f7b27d04516a405128a4f5886fe

**Comment by afzal442** [comment] 2021-08-04 06:10
hope it'll clear/

**Comment by afzal442** [comment] 2021-08-05 08:02
@Nikhil-Ladha could u verify that?

**Comment by warunicorn19** [comment] 2021-08-07 16:23
@afzal442 @Nikhil-Ladha @sudo-NithishKarthik is anyone working on this issue?? if not i would love to work on this.

**Comment by sudo-NithishKarthik** [comment] 2021-08-07 16:27
Sure @afzal442 , go ahead. Definitely the navigation issue has to be fixed

**Comment by sudo-NithishKarthik** [comment] 2021-08-07 16:27
But i am not sure about the alignment tho 🤔 
// @Nikhil-Ladha

**Comment by Nikhil-Ladha** [comment] 2021-08-07 16:36
For the alignment part, only the margin around the heater can be reduced a bit. It is fine if the sidebar is aligned to the content and not the header.

**Comment by afzal442** [comment] 2021-08-07 16:37
sorry pals, I am already assigned to other issues. till then you @warunicorn19 can work on it.

**Comment by warunicorn19** [comment] 2021-08-07 16:42
yeah, so i can get this done.
So,

- [ ] The margin needs to be fixed.
- [ ] The navigation of the links should lead to the right place.

yes? anything else?

**Comment by Nikhil-Ladha** [comment] 2021-08-07 16:43
Only the above 2 :)

**Comment by warunicorn19** [comment] 2021-08-07 16:44
Cool, will get it done, as soon as i can :)

**Comment by warunicorn19** [comment] 2021-09-08 18:26
Ugh I completely forgot about this🤦.

**Comment by warunicorn19** [comment] 2021-09-08 19:10
@Nikhil-Ladha are we removing the TOC as discussed on the websites' call?

**Comment by warunicorn19** [comment] 2021-09-08 19:11
Then we can close this issue

**Comment by Nikhil-Ladha** [comment] 2021-09-08 19:20
Yeah, just don't remove the code only comment it out.

**Comment by warunicorn19** [comment] 2021-09-08 20:22
Yes, don't worry😅.

**Closed** 2021-09-10 18:18 UTC
Labels: kind/enhancement, language/javascript
