### ISSUE TITLE
[Performance] Avoid showing invisible text while custom fonts load

### ISSUE THREAD

**Issue by YashKamboj** [layer5io/layer5#3006] opened 2022-08-02 11:44 UTC
**Current Behavior**

Fonts are often large files that take a while to load. Which slows the performance 
**Desired Situation**

The easiest way to avoid showing invisible text while custom fonts load is to temporarily show a system font. By including font-display: swap in your @font-face style, you can avoid FOIT in most modern browsers. [Resource ](https://web.dev/font-display/?utm_source=lighthouse&utm_medium=lr#how-to-avoid-showing-invisible-text)
---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment] 2022-08-02 12:00
@YashKamboj This looks like a duplicate issue.

Also, note the use of heading style in the description.

**Comment by leecalcote** [comment] 2022-08-02 12:01
Duplicate of https://github.com/layer5io/layer5/issues/2996

**Closed by leecalcote** 2022-08-02 12:01 UTC
Labels: issue/duplicate, good first issue, kind/chore
