### ISSUE TITLE
Addition of community calendar on Layer5-NG site

### ISSUE THREAD

**Issue by Neilblaze** [layer5io/layer5#934] opened 2020-10-07 14:11 UTC
**Current Behavior**

Addition of a community calendar in the community section on our website is a much needed.

Soon we will be having more WG meetings in a week & having a calendar on our website will get our **new** & existing contributors more acquainted with same.

**Desired Behavior**

- A full-calender is suggested to be added to the Community & Events page of our new Layer5-ng site.
- Something like [this](https://fullcalendar.io/#demos)!
---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by vinayaksh42** [comment] 2020-10-15 17:56
Do we include this calendar on the main community landing page or making a separate route for only displaying the calendar itself?

**Comment by Neilblaze** [comment] 2020-10-15 18:00
The calendar has some API issues. For now, it'll be great if we can add the calendar to the community page as a modal preview.

@Nikhil-Ladha what say?

**Comment by Nikhil-Ladha** [comment] 2020-10-24 13:56
Why modal?
Better to display it completely on the webpage itself and the preview in the description of the issue is a nice one, if something like that can be achieved it would be best!

**Comment by leecalcote** [comment] 2020-11-14 12:51
Challenges with the calendar api have been overcome. This issue is ready for implementation.

**Comment by Jashpatel1** [comment] 2020-12-03 06:03
@Neilblaze @vinayaksh42 Any progress here?

**Comment by Jashpatel1** [comment] 2020-12-31 07:02
Closing with #1318

**Closed by Jashpatel1** 2020-12-31 07:02 UTC
Labels: framework/gatsby, framework/react, hacktoberfest, kind/enhancement, layer5-ng
