### ISSUE TITLE
[Blog] "SMI Conformance Testing with Meshery" missing feature image for social shares

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#644] opened 2020-08-18 23:12 UTC
**Description**
When @nveenjain's blog post is shared on Twitter, and I suspect on LinkedIn, the featured image isn't retrieved and shown.

<img width="615" alt="Screen Shot 2020-08-18 at 5 44 15 PM" src="https://user-images.githubusercontent.com/7570704/90574281-24ef1a80-e17e-11ea-8854-9baafbef745d.png">

**Expected Behavior**
This post should be updated to specify an image for Twitter to use when it unfurls / shows a preview.

**Comment by Nikhil-Ladha** [comment] 2020-10-31 07:56
I just checked on this one @leecalcote and found a bug in the UI of Twitter :laughing: something similar to what we faced for our NG site. The image is not displayed because the feature image is an SVG, but the image comes up if it's a JPG, PNG. I even reported it to Twitter, lets see if they revert back :smile:

**Comment by leecalcote** [comment] 2020-11-03 02:56
@Nikhil-Ladha argh. It's surprising that SVGs aren't supported. :/

**Comment by Nikhil-Ladha** [comment] 2020-11-03 03:52
Closing this one, as it's not a bug from our end.

**Closed by Nikhil-Ladha** 2020-11-03 03:52 UTC
Labels: kind/bug
