### ISSUE TITLE
[Ng] Mute language flag colors

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#797] opened 2020-09-21 18:55 UTC
**Current Behavior**
The language flags in the layer5-ng site footer draw much of the visitors attention unnecessarily. On the current layer5.io site, we have intentionally muted the colors of the language flags (as an infrequently used utility) as their full color draws too much attention and distracts users from what we want really want to draw them into (the twitter feed or other links). 

**Desired Behavior**
Mute flag colors (and opacity?) similar to what has been done on the current layer5.io site. Reference: https://github.com/layer5io/layer5/pull/762#pullrequestreview-487338158

[Optional] **Alternatives**
Remove language flags altogether. I'm not convinced that these are necessary or that this functionality couldn't be just as well delivered via a drop-down list, so as to still offer the functionality, but not take up so much real estate on the page

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by kishore007k** [comment] 2020-09-21 20:32
If the issue is still open I'm up for this!.
This is what it should look like right? @leecalcote 
![ScreenShot](https://user-images.githubusercontent.com/34863222/93818152-9cc9cc80-fc77-11ea-98c2-b53339f47346.PNG)

**Comment by leecalcote** [comment] 2020-09-21 20:38
@kishore007k, thanks for jumping in here. 

Yes, that's about right. I wonder what happens if we incorporate grayscale into these. I'll dig up an example of this being done previously....

**Comment by leecalcote** [comment] 2020-09-21 20:39
Here we are - https://github.com/layer5io/layer5/commit/1203159bf2a321a2ccea4dd156a44b14f1c12e3a#diff-7693eb643e8fe8b8d46b407909b408ceR87

**Comment by kishore007k** [comment] 2020-09-21 20:41
Thanks for the reference. @leecalcote 
Actually that is what I have done in this.

**Comment by Tanuj22** [comment] 2020-09-24 10:35
Fixed in #811

**Closed** 2020-09-24 10:35 UTC
Labels: framework/gatsby, help wanted, kind/enhancement, language/html, language/javascript, layer5-ng
