### ISSUE TITLE
Add spacing on Recognition page

### ISSUE THREAD

**Issue by ritiksaxena124** [layer5io/layer5#5520] opened 2024-05-02 09:13 UTC
### Current Behavior
There is no spacing between the badges  on the [recognition page](https://layer5.io/community/handbook/recognition)
![image](https://github.com/layer5io/layer5/assets/51539117/014a20b9-3996-4f11-a0fb-6ea234053a13)

### Desired Behavior
Add spacing between the badges of `1rem`

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by vishalvivekm** [comment] 2024-05-06 11:16
@Satakshijain 
Do you have any update that you want to share today on websites call [5:30 PM IST] ?
Meeting minutes: https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit

**Comment by vishalvivekm** [comment] 2024-05-13 06:29
@Satakshijain are you still working on the issue ? Please sound off whether or not, we need to re-assign the task.

**Comment by Ashparshp** [comment] 2024-05-14 17:28
Hey @bunnyDasari The exact location of the issue is in the src/sections/Community/Handbook/recognition.js file. Since Ritik might be busy, I'm letting you know. If you're interested in working on it, we can assign it to you.

**Comment by bunnyDasari** [comment] 2024-05-14 17:31
@Ashparshp yeah I'm interested assign to me

**Comment by Ashparshp** [comment] 2024-05-14 17:34
@BunnyDasari, great to hear you're interested! I've assigned the task to you. Thanks for stepping up!

**Comment by bunnyDasari** [comment] 2024-05-15 03:05
@Ashparshp yeah i will work on this issue

**Comment by vishalvivekm** [comment] 2024-05-18 14:20
@bunnyDasari 

Let's discuss your progress on the issue so far in the next websites meeting on Monday.
Meeting minues: https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit

**Comment by bunnyDasari** [comment] 2024-05-19 10:03
> @bunnyDasari
> 
> Let's discuss your progress on the issue so far in the next websites meeting on Monday. Meeting minues: https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit

@vishalvivekm  can you please help me out to fill this form im ubale to understand the google document

**Comment by AbhinavKRN** [comment] 2024-07-09 18:58
Hey, Can you assign this issue to me?

**Comment by Ashparshp** [comment] 2024-07-09 20:43
@AbhinavKRN Thanks for showing your interest.. @bunnyDasari 
any update on this issue? If not, we'll assign it to @AbhinavKRN.

**Comment by bunnyDasari** [comment] 2024-07-10 01:18
@Ashparshp the issue was resolved.i have made a PR  #5641

**Comment by Ashparshp** [comment] 2024-07-10 04:49
@bunnyDasari Sign-off please!

**Comment by bunnyDasari** [comment] 2024-07-10 04:54
@Ashparshp okay

**Comment by Ashparshp** [comment] 2024-07-16 10:32
@bunnyDasari Reminder!!

**Comment by Aarya01Patil** [comment] 2024-08-04 14:09
@Ashparshp Hey can i work on this issue

**Comment by Ashparshp** [comment] 2024-08-05 05:11
@bunnyDasari, as we haven't heard back from you, we're reassigning this issue to @Aarya01Patil.

**Closed** 2024-08-06 05:24 UTC
Labels: kind/enhancement, good first issue, component/ui
