### ISSUE TITLE
[Landscape] Update Service Mesh Timeline Projects

### ISSUE THREAD

**Issue by PluckyPrecious** [layer5io/layer5#674] opened 2020-08-25 10:41 UTC
**Current State:**
The service mesh timeline (project announcement) section is missing OSM, KUMA, etc.

**Desired State:**
Update by adding the missing projects to the timeline.

**Contributor Resources**
- [Instructions for updating the landscape](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#updating-the-service-mesh-landscape)Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).

**Comment by leecalcote** [comment] 2020-08-25 11:46
Thank you, @PluckyPrecious. These are much needed. Microsoft committed to PRing for OSM. Kong's CTO recently refreshed Kuma's details (two weeks ago) just before this timeline was released.

@Nikhil-Ladha I didn't realize that our last PR here actually published the timeline. It's good for us to move forward. We need to circle back to fix a few items on the timeline.
- Less whitespace between mesh name and announce date
- removal of the vertical scrollbar for this section.

**Comment by Nikhil-Ladha** [comment] 2020-08-25 12:20
Yeah, @leecalcote i know that. I even thought of providing a fix for that in this weekend but was facing some issue with my laptop and was not able to do so. Will update it ASAP.

**Comment by Nikhil-Ladha** [comment] 2020-08-25 12:23
That's the reason I have not closed the issue #647 yet.

**Comment by PluckyPrecious** [comment] 2020-08-25 14:50
> Yeah, @leecalcote i know that. I even thought of providing a fix for that in this weekend but was facing some issue with my laptop and was not able to do so. Will update it ASAP.

Sorry about your laptop issue @Nikhil-Ladha , Umm I'd like to know about the triangle at the top of the timeline, Is that the style? If not, can it be well aligned to the center of the timeline, I feel it's about to fall off. 😆

**Comment by Nikhil-Ladha** [comment] 2020-08-25 15:10
In which view exactly do you get such feeling?

**Comment by Nikhil-Ladha** [comment] 2020-08-25 15:11
Also, I know there are still a bit of issues with the timeline and I will be updating it sooon, as I mentioned above.

**Comment by PluckyPrecious** [comment] 2020-08-25 16:56
> In which view exactly do you get such feeling?

The triangle here 
![0966416A-7F80-4B50-9E70-32B7E427F37F](https://user-images.githubusercontent.com/59584014/91203761-39da2980-e6fb-11ea-943c-89d9cb5a4080.jpeg)

**Comment by leecalcote** [comment] 2020-08-25 16:58
While you're receiving feedback, @Nikhil-Ladha.... :).... Could we try a different color for the circular points in the timeline?

**Comment by Nikhil-Ladha** [comment] 2020-08-25 17:08
> While you're receiving feedback, @Nikhil-Ladha.... :).... Could we try a different color for the circular points in the timeline?

Sure!

**Comment by PluckyPrecious** [comment] 2020-08-25 17:12
> > In which view exactly do you get such feeling?
> 
> The triangle here
> ![0966416A-7F80-4B50-9E70-32B7E427F37F](https://user-images.githubusercontent.com/59584014/91203761-39da2980-e6fb-11ea-943c-89d9cb5a4080.jpeg)

I also think some of the circles are kinda off 🙂, It’s probably meant to be placed on the side of each chat box, just like the second one which is perfect. But the 1st, 3rd circle... aren’t well placed.

**Comment by leecalcote** [comment] 2020-09-30 23:40
@PluckyPrecious these items might be finished now. Will you double-check and close, if so?

**Comment by Nikhil-Ladha** [comment] 2020-10-01 04:06
@leecalcote the design issue is resolved but the addition of data is still left, that's the reason the issue is kept in Open state till now.

**Comment by Nikhil-Ladha** [comment] 2020-10-02 13:15
@leecalcote we don't have data for Kuma to add it in the timeline can you please update that?
Or share that I will update it then.

**Comment by leecalcote** [comment] 2020-10-02 13:40
Is is just announce date that we're in need of?

**Comment by leecalcote** [comment] 2020-10-02 13:42
@Nikhil-Ladha Sep 10, 2019 announce date for Kuma

**Comment by Nikhil-Ladha** [comment] 2020-10-02 14:33
Yeah...cool will submit a PR ASAP.

**Closed** 2020-10-02 20:08 UTC
Labels: area/landscape, framework/jekyll, hacktoberfest, help wanted
