### ISSUE TITLE
[Footer] Subscribe component overlaps on zoom greater than 100%

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3865] opened 2023-03-02 18:35 UTC
### Description
When a site visitor has their browser zoom level at a level higher than 100%, the subscribe component overlaps other elements in the footer.

### Expected Behavior
No overlap.

### Screenshots
<img width="1380" alt="Screenshot 2023-03-02 at 12 32 40 PM" src="https://user-images.githubusercontent.com/7570704/222520298-532e530b-e4de-440b-b0ff-7beb4a5e38b9.png">

### Environment:
- Host OS: macOS
- Browser: Safari

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Srinja333** [comment] 2023-03-02 18:41
can i work on this?

**Comment by sambhavgupta0705** [comment] 2023-03-02 18:43
Hey @leecalcote Can I work on this one.

**Comment by leecalcote** [comment] 2023-03-02 18:51
Proceeding in chronological order...

**Comment by Anishsme** [comment] 2023-03-05 14:22
Can I please be next in line to work on this ?

**Comment by Srinja333** [comment] 2023-03-09 04:55
i am a window user how to test it in safari, i have downloaded safari but it does not work properly ?

**Comment by Nikhil-Ladha** [comment] 2023-03-09 18:08
@sambhavgupta0705 , @Anishsme , @Darrendsouza1111 does either of you have access to Safari?

**Comment by Darrendsouza1111** [comment] 2023-03-10 02:43
> @sambhavgupta0705 , @Anishsme , @Darrendsouza1111 does either of you have access to Safari?

i dont.Is there any alternative way?

**Comment by UsmanDev09** [comment] 2023-03-22 07:07
Can I work on this? @leecalcote @Nikhil-Ladha

**Comment by Nikhil-Ladha** [comment] 2023-03-22 07:19
@UsmanDev09 do you have access to Safari? And, do you have the site up and running locally?

**Comment by UsmanDev09** [comment] 2023-03-22 08:14
I do have site up and running locally on linux. But, if i need to have
access to Safari, I can set up my the environment on Macbook too

**Comment by Nikhil-Ladha** [comment] 2023-03-22 09:02
> I do have site up and running locally on linux. But, I I can set up my environment on Macbook too to access Safari

The thing is the issue is reproducible only on Safari, so you need access to Safari to fix this issue properly.
That said, once you havee the site setup done on Mac, let me know I will assign the issue to you.

**Comment by Gaurav-08-dev** [comment] 2023-04-05 08:29
Hey @Nikhil-Ladha , is this issue resolved ? As I setup up the project locally and tried recreating the bug on safari, there is no overlapping of subscribe component on zoom greater than 100%

**Comment by chiragchhabria2** [comment] 2023-04-20 11:53
Hey, can I get this? I have already fixed the issue in my local repo.

**Comment by nakulbh** [comment] 2023-07-23 06:37
HEY @leecalcote is issue still open to work ?

**Comment by leecalcote** [comment] 2023-07-23 22:57
@nakulbh yes, will you review @chiragchhabria2’s open PR?

**Comment by nakulbh** [comment] 2023-07-24 22:30
@nakulbh yes sir I can review his PR

**Comment by abhijeetgauravm** [comment] 2023-09-04 09:31
@nakulbh  This issue is only reproducible on Safari, as mentioned by @Nikhil-Ladha. Do you have access to Safari?

**Comment by MohitGupta14** [comment] 2023-10-19 06:12
I would like to work on this issue, I have access to macOS. 
Kindly assign to me if it is available @leecalcote

**Comment by abhijeetgauravm** [comment] 2023-10-19 06:24
There u go @MohitGupta14

**Comment by MohitGupta14** [comment] 2023-10-19 15:59
Tested with the latest version of Safari and macOS, and everything is working fine. The footer is aligning perfectly. Please see the screen recording for confirmation. Let me know if I am doing anything incorrectly. 

https://github.com/layer5io/layer5/assets/81846020/09b5c58b-2c79-499b-9794-7e72fb99e8ca

**Comment by leecalcote** [comment] 2023-10-19 16:03
The issue occurs between 1200px and 1100px.

**Comment by Ashparshp** [comment] 2023-11-30 23:06
Hi all,

I've noticed the ongoing discussion on issue #3865 regarding the [Footer] Subscribe component overlapping problem. If this issue is still pending or unassigned, I'm ready to take it on. I've previously worked on a similar matter (#4768) and can jump in to assist.

Let me know if I can get started on resolving this.

@abhijeetgauravm @leecalcote

**Comment by saurabh100ni** [comment] 2024-01-04 15:50
This issue has been open for some time with no recent activity, unassigning to open it up for new contributors to give it a go.

**Comment by Ashparshp** [comment] 2024-01-04 15:56
@saurabh100ni May i?

**Comment by Ashparshp** [comment] 2024-01-04 19:05
@saurabh100ni @leecalcote Please review the changes in the media query for screens between 704px and 1199px.
and confirm that the adjustments resolve the reported issue.

**Comment by saurabh100ni** [comment] 2024-01-04 19:32
Thank you for the PR @Ashparshp. LGTM.

**Comment by iArchitSharma** [comment] 2024-01-29 15:47
Fixed

**Closed by iArchitSharma** 2024-01-29 15:47 UTC
Labels: kind/bug, help wanted, good first issue, language/css
