### ISSUE TITLE
[Component Styling] Enhance FeaturesContainer to allow for selective styling

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#5229] opened 2023-12-22 20:31 UTC
### Current Behavior
Unable to style words within the `descr` property of the FeaturesContainer component.

### Desired Behavior
It'd be great to be able to style words within the descriptions here - https://github.com/layer5io/layer5/blob/master/src/sections/Home/FeaturesContainer/index.js#L45-L46. Like putting italics around the word "and".

### Screenshots / Mockups

![Screenshot 2023-12-22 at 2 25 25 PM](https://github.com/layer5io/layer5/assets/7570704/e6e517af-0a77-4559-95e3-00367bf1732c)

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by horizenight** [comment] 2023-12-22 22:00
Fix:  use this formatting style : ) opens to a lot of formatting abilities to the text
```js
 desc: (
        <span>
          Incorporate AWS and GCP components into Meshery designs for comprehensive and intuitive system mapping, documentation, <i>and</i> orchestration.
        </span>
      ),
   ```
   
   instead of : 
   ```
   desc: "Incorporate AWS and GCP components into Meshery designs for comprehensive and intuitive system mapping, documentation, and orchestration.",
   ```

**Comment by kishore2k** [comment] 2023-12-23 07:41
if the issue is yet to be solved, can i take up this issue ?

**Comment by AllenOps08** [comment] 2024-03-11 07:40
Is this issue solved ?

**Comment by RafaelJohn9** [comment] 2024-04-28 12:12
@leecalcote  if the issue hasn't been solved I would like to work on it

**Comment by leecalcote** [comment] 2024-04-28 13:07
@iArchitSharma will you please triage?

**Comment by iArchitSharma** [comment] 2024-04-28 19:37
@leecalcote Done merged

**Closed** 2024-04-28 19:36 UTC
Labels: kind/enhancement, help wanted, framework/gatsby, language/css
