### ISSUE TITLE
[UI] Title image for all events on the Layer5 are getting out of position

### ISSUE THREAD

**Issue by sidd-oo** [layer5io/layer5#2640] opened 2022-03-06 12:01 UTC
**Description**
The title image for all events on the Layer5 is getting out of position. 
Below are some examples : 
1) [Project Office Hours: Service Mesh Performance at KubeCon NA 2021](https://layer5.io/community/events/project-office-hours-service-mesh-performance-at-kubecon-na-2021)
2) [KubeCon China 2021](https://layer5.io/community/events/kubecon-china-2021)
3) [DEVCONF 2022](https://layer5.io/community/events/devconf-2022)

**Expected Behavior**
The title image for all the events needs to be aligned centrally.

**Screenshots**
![image](https://user-images.githubusercontent.com/25115188/156922078-c955832f-720b-43ce-a663-a8738209adfb.png)

**Environment:**
- Host OS:  Windows
- Browser:  Chrome

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Akshit42-hue** [comment] 2022-03-06 12:12
Can I work on this issue @sidd-oo

**Comment by Abhijay007** [comment] 2022-03-06 12:13
sure @Akshit42-hue , go ahead :)

**Comment by Nikhil-Ladha** [comment] 2022-03-06 12:33
Also, fix the alignment on the [Events](https://layer5.io/community/events) page. A `max-height` with `cover` property would do, for the images in the slider.

**Comment by Akshit42-hue** [comment] 2022-03-06 14:54
Can you give some more information about cover property @Nikhil-Ladha

**Comment by Nikhil-Ladha** [comment] 2022-03-06 15:00
I am talking about the `object-fit: cover` CSS property.

**Comment by vermaayush680** [comment] 2022-03-06 19:24
Hi @Nikhil-Ladha , Can you assign this issue to me.
Also do you want the images to take 100% screen with or remain the same size?

**Comment by Nikhil-Ladha** [comment] 2022-03-07 03:58
> Hi @Nikhil-Ladha , Can you assign this issue to me. Also do you want the images to take 100% screen with or remain the same size?

Hi @vermaayush680 , the issue is already been worked upon by another contributor, so unfortunately I can't assign it to you. You can checkout other open issues in the repo.

**Comment by Akshit42-hue** [comment] 2022-03-07 14:57
Update:
![Screenshot from 2022-03-07 20-23-20](https://user-images.githubusercontent.com/59443454/157058398-d4af26b7-058b-4e52-9b95-1ee22ed00728.png)
Does this looks good to you or  need any changes @Nikhil-Ladha

**Closed** 2022-03-14 13:23 UTC
Labels: kind/bug, good first issue, openforce
