### ISSUE TITLE
Unable to horizontal scroll 'Service Mesh Interface Compliance' table in mobile device

### ISSUE THREAD

**Issue by divz-codess** [layer5io/layer5#3826] opened 2023-02-25 22:34 UTC
### Description

While using a mobile device the Service Mesh Interface Compliance table isn't scrolling and we cannot see the columns to the right.
on the page [https://layer5.io/service-mesh-landscape](https://layer5.io/service-mesh-landscape)

### Expected Behavior

The table should scroll towards the right to view the rest of the columns.

### Screenshots

https://user-images.githubusercontent.com/88512639/221382563-9c90bd83-5acf-49e1-aa47-86945bea4c44.mp4

### Environment:
- Host OS: Android
- Browser: Chrome

I am working on this issue

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Hussain0520** [comment] 2023-02-26 08:27
Hey I would like to contribute to this issue

**Comment by Avi-88** [comment] 2023-02-26 15:14
Hi @Hussain0520 , If you do end up working on this issue while you are at it  would you please also fix the legend rows to be consistent. Right now the content isn't aligned , It should look more like below , thanks

![image](https://user-images.githubusercontent.com/79744258/221419154-5a0d1971-da9e-40d7-8767-2012811c3c58.png)

**Comment by divz-codess** [comment] 2023-02-26 16:40
@Hussain0520 I'm already working on this issue. Thanks for the interest :)

**Comment by Avi-88** [comment] 2023-02-27 05:09
Hi @divz-codess , I just noticed that this is a duplicate of [#3788](https://github.com/layer5io/layer5/issues/3788). There is no one actively working on the other issue so you should be fine but in future  please do check for duplicates before opening a new issue to avoid confusion and wasted efforts. As you are already working on a fix for this I'll try and get the other one closed for now, also do consider the suggestion I mentioned above regarding the legend contents not being aligned , thanks

**Comment by divz-codess** [comment] 2023-02-27 06:52
Thanks for assigning me @Nikhil-Ladha. Will surely keep this in mind in the future @Avi-88 thanks 😊

**Comment by oneknucklehead** [comment] 2023-02-27 20:21
> Hi @divz-codess , I just noticed that this is a duplicate of [#3788](https://github.com/layer5io/layer5/issues/3788). There is no one actively working on the other issue so you should be fine but in future please do check for duplicates before opening a new issue to avoid confusion and wasted efforts. As you are already working on a fix for this I'll try and get the other one closed for now, also do consider the suggestion I mentioned above regarding the legend contents not being aligned , thanks

closed the other one!

**Comment by AkashS20** [comment] 2023-04-11 15:36
I'd like to work on this issue

**Closed** 2023-04-12 18:48 UTC
Labels: kind/bug, help wanted, good first issue, area/landscape
