### ISSUE TITLE
Add more partner logos to the collaborating section

### ISSUE THREAD

**Issue by Shubhcs01** [layer5io/layer5#3133] opened 2022-08-31 16:01 UTC
#### Current Behavior

We have a set of partners whose logos are shown under the collaborating section of the home page.

![Screenshot 2022-08-31 203952](https://user-images.githubusercontent.com/81324145/187722722-3bd50cef-7dcb-4786-996f-54ced7513436.png)

#### Desired Behavior

Add more partner logos.
To start off with, add Docker's logo and F5's logo.

---

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by adarsh500** [comment] 2022-08-31 16:47
Can I work on this issue?

**Comment by leecalcote** [comment] 2022-08-31 16:59
Thank you for filing this issue, however, this is actually by design as we're not trying to list all partners, users, customers and so the effect is just that of cutting off the list at some point. We need to add more logos in order to have that sense conveyed in the two row view. That's what we should focus on in this issue. To start, let's add Docker's logo and F5's logo.

**Comment by Shubhcs01** [comment] 2022-08-31 17:38
> Thank you for filing this issue, however, this is actually by design as we're not trying to list all partners, users, customers and so the effect is just that of cutting off the list at some point. We need to add more logos in order to have that sense conveyed in the two row view. That's what we should focus on in this issue. To start, let's add Docker's logo and F5's logo.

Okay, I get it. 
So, just to clarify I have to add Docker and F5's logo in the partner section right?

**Comment by tinniaru3005** [comment] 2022-09-08 21:47
Hey @Shubhcs01 ! I am new to the community and want to work on this issue. Can you please assign it to me?

**Comment by leecalcote** [comment] 2022-09-08 21:48
Thanks for raising your hand, @tinniaru3005. 👍 Please note that the requirement has shifted.

**Comment by tinniaru3005** [comment] 2022-09-08 22:32
> Thanks for raising your hand, @tinniaru3005. 👍 Please note that the requirement has shifted.

Hello @leecalcote . Thanks for assigning the issue to me. Can you please explain to me the current requirements? I also wanted to confirm if the changes are required on [this page](https://layer5.io/projects).
![layer5](https://user-images.githubusercontent.com/62856848/189237432-dfd9c698-b14f-43a3-b9e7-3771edd248e5.png)

**Comment by leecalcote** [comment] 2022-09-09 03:11
@tinniaru3005, not quite. Thanks for jumping in.  The page that you’re referring to is the project page. The page in question is the homepage. Two new logos are requested. They must be SVGs and grayscaled.

**Comment by Shubhcs01** [comment] 2022-09-09 18:50
> Hey @Shubhcs01 ! I am new to the community and want to work on this issue. Can you please assign it to me?

Hi @tinniaru3005 , first of all welcome to the community 🤝. I am slight busy in some college works so yeah please go on and solve the issue. Also if you need any help just drop a comment. Thanks @leecalcote for explaining the issue.🙂

**Comment by Nikhil-Ladha** [comment] 2022-09-30 05:46
Clearing assignees to allow others for taking it.

**Comment by SaiRev0** [comment] 2022-10-01 12:03
Hello @Nikhil-Ladha and @leecalcote, If no one is working on the Issue can You assign the issue to me? I m new to the community

**Comment by Nikhil-Ladha** [comment] 2022-10-01 13:36
Yes, @SaiRev0 you can work on this.
Though, the requirement is slightly different as mentioned in this [comment](https://github.com/layer5io/layer5/issues/3133#issuecomment-1233191687)

**Comment by legendarykamal** [comment] 2022-10-03 17:41
@Nikhil-Ladha can you preferably update the issue title and desc as per this comment https://github.com/layer5io/layer5/issues/3133#issuecomment-1233191687 so that there's no confusion.

(I am not able to edit it)

**Comment by SaiRev0** [comment] 2022-10-08 09:17
@Nikhil-Ladha So I have to add 1 more row for the logos of the partners??

am I correct with that??

**Comment by Nikhil-Ladha** [comment] 2022-10-08 10:17
Yes, and probably move a couple of them in the above row, to the new one.

**Comment by AbhishekTiwari23** [comment] 2022-10-08 14:47
> Yes, and probably move a couple of them in the above row, to the new one.

Hello @Nikhil-Ladha, I have a suggestion. Can he add a sliding effect instead of diving it between two rows? This will look good, I think.
If I can contribute, then please let me know.

**Comment by Nikhil-Ladha** [comment] 2022-10-08 14:52
Nope, the overflow is by design and intentional

**Comment by AbhishekTiwari23** [comment] 2022-10-08 15:20
> Nope, the overflow is by design and intentional

Ok, thanks. But if the issue exists, then my setup is ready

**Comment by SaiRev0** [comment] 2022-10-08 23:19
@Nikhil-Ladha had some issues where I can get help ??

**Comment by legendarykamal** [comment] 2022-10-09 03:31
@SaiRev0 ask in a public slack channel like #websites channel by tagging appropriate person to whom you would like to ask.

**Comment by SaiRev0** [comment] 2022-10-11 18:18
@Nikhil-Ladha please provide the photos and details of all the collaborating companies so that I can add them

**Comment by Nikhil-Ladha** [comment] 2022-10-11 18:26
@leecalcote ^^

**Comment by Nikhil-Ladha** [comment] 2022-10-11 18:27
For the logo, you could download them from their respective sites docker.com and f5.com

**Comment by SaiRev0** [comment] 2022-10-11 19:03
@Nikhil-Ladha So I have to add only 2 more logos.

So I will add them and shift some from the top so both the rows will have the same numbers

Can we chat some else the comments will go long 😅

**Comment by Nikhil-Ladha** [comment] 2022-10-11 19:09
Yes.
If you have more doubts ping me on slack.

**Comment by SaiRev0** [comment] 2022-10-12 20:47
![image](https://user-images.githubusercontent.com/96655163/195444567-e1ceb3fd-c788-48b8-8dfc-0d2ed7f95e12.png)

Does it look fine??

**Comment by leecalcote** [comment] 2022-10-12 21:03
@SaiRev0, it's looking good to me... so long as you're allowing the logos full span of the page (even to the extent that they get cutoff (that's fine).

**Comment by leecalcote** [comment] 2022-10-12 21:04
The significant size difference between the circular Citrix and the circular F5 logos.... hmm. All should be allowed the same space, which means that two circular logos should essentially be of the same size. Cut out any extra padding in the F5 SVG, if needed.

**Comment by SaiRev0** [comment] 2022-10-12 21:38
> @SaiRev0, it's looking good to me... so long as you're allowing the logos to full span of the page (even to the extent that they get cut off (that's fine).

Ok I will try and adjust the 6 logos to take the full-screen size 

And about the logo size I will fix the f5 logo

**Comment by leecalcote** [comment] 2022-10-12 21:39
@SaiRev0 thanks... although, there should need to be a change to the existing logos, I don't believe.

**Comment by SaiRev0** [comment] 2022-10-12 21:40
> @SaiRev0 thanks... although, there should need to be a change to the existing logos, I don't believe.

So do I have to change some logos (old logos) or leave it as it is?

**Comment by UtkarshMishra12** [comment] 2022-12-23 19:09
@leecalcote @SaiRev0 ^^

**Comment by legendarykamal** [comment] 2022-12-23 19:15
@UtkarshMishra12 I believe this issue has already been taken care of in another PR and hence can be closed successfully.

Thank you for your contributions.

**Closed by legendarykamal** 2022-12-23 19:15 UTC
Labels: kind/enhancement, hacktoberfest, framework/gatsby, area/partners, issue/remind
