### ISSUE TITLE
Misalignment in 

### ISSUE THREAD

**Issue by VivekBaldha0712** [layer5io/layer5#4822] opened 2023-09-04 12:38 UTC
### Description

This "Subscribe to our News Letter" is rightly aligned. It should be in the center.
### Screenshots

![image](https://github.com/layer5io/layer5/assets/86009821/354d8816-193e-4c7b-94d0-101f7ff013b2)

### Environment:
- Host OS: Windows 10
- Browser:Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by mikenrowland** [comment] 2023-09-04 16:56
I don't think it looks better aligned to the right when there is nothing on the left. That doesn't conform to the balance of the two other div blocks above it where you have everything evenly positioned across the width of the screen. The centre alignment would be the most appropriate position.

This passes for a good first issue @VivekBaldha0712, can you kindly assign this to me? Thanks

**Comment by leecalcote** [comment] 2023-09-04 19:51
@vishalvivekm

**Comment by Kkotiswar** [comment] 2023-09-07 22:35
Hello @leecalcote  I have fixed this bug and aligned that div to the center 

![image](https://github.com/layer5io/layer5/assets/76087446/d88ac326-e7c5-48bb-b21c-c47af4bf569a)

I am gonna create the pull request if this is looking fine. 

waiting for the response

**Comment by Kkotiswar** [comment] 2023-09-08 09:19
@mikenrowland Thank you for bringing this to my attention. I apologize for any oversight. I will refrain from opening a pull request for unassigned issues in the future, and I appreciate your guidance on adhering to community rules.

**Comment by vishalvivekm** [comment] 2023-09-08 13:35
> @mikenrowland Thank you for bringing this to my attention. I apologize for any oversight. I will refrain from opening a pull request for unassigned issues in the future, and I appreciate your guidance on adhering to community rules.

@Kkotiswar It's important to request assignment before starting work on an issue if there is no assignee.

Please go through the [contributing guidelines](https://layer5.io/community/handbook/contribution) and code of conduct outlined in the [community handbook](https://layer5.io/community/handbook).
Also refer to https://layer5.io/community/handbook/faq to know how to approach working on issues within the community, I hope you'll keep these in mind for future.

**Comment by vishalvivekm** [comment] 2023-09-08 13:37
Regarding aligning the "Subscribe to our News Letter" in center, Yeah it looks good to me.
Thoughts @Mohith234 ? // @mikenrowland

**Comment by Mohith234** [comment] 2023-09-08 13:55
Yeah looks good to me too @vishalvivekm

**Comment by mikenrowland** [comment] 2023-09-08 19:48
Yeah, I totally agree with putting the "Subscribe to our News Letter" text in the centre. @vishalvivekm

**Comment by VivekBaldha0712** [comment] 2023-09-09 04:32
I want to work on this. Can you assign this task to me ?

**Comment by VivekBaldha0712** [comment] 2023-09-24 15:52
Please assign this task @leecalcote @Chadha93

**Comment by Chadha93** [comment] 2023-09-24 15:59
> Please assign this task @leecalcote @Chadha93

@VivekBaldha0712, there is already an open pr on this issue, also this is by design (right aligned). Issue invalid. Open a poll on discuss.layer5.io, if you think to change this to center.

**Comment by VivekBaldha0712** [comment] 2023-09-24 16:06
PR is raised before the assignment.

**Closed** 2023-10-23 12:16 UTC
Labels: kind/bug
