### ISSUE TITLE
[Bug] Refine related post on news

### ISSUE THREAD

**Issue by legendarykamal** [layer5io/layer5#3163] opened 2022-09-09 14:33 UTC
#### Description

Related post should not include the current post.

#### Expected Behavior

Refinement needed.
#### Screenshots

![image](https://user-images.githubusercontent.com/95926324/189374259-d1a265b1-2ba7-45bf-a1e3-54883d92d5f2.png)

![image](https://user-images.githubusercontent.com/95926324/189374331-4ee7969b-7a6a-44a4-9ec3-6660436a40b1.png)

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by sam1code** [comment] 2022-09-11 00:14
Hii @legendarykamal can you please send me the exact post because I'm unable to reproduce the bug for other cases...

**Comment by legendarykamal** [comment] 2022-09-11 08:58
hi @sam1code thank you for showing interest, It can be performed on all the latest news . 

I am working currently to fix this.

**Comment by sam1code** [comment] 2022-09-11 09:07
@legendarykamal welcome🥰

**Comment by OmiCoding** [comment] 2022-10-23 01:02
If this is still open I would like to be assigned to this issue.

**Comment by UtkarshMishra12** [comment] 2022-12-23 19:40
@leecalcote Is this still valid?

**Comment by leecalcote** [comment] 2022-12-23 20:05
Sure, yes, @UtkarshMishra12.

@legendarykamal seems to have moved on from the community, though, and so hopefully, another contributor picks it up.

**Comment by gurpreet-legend** [comment] 2023-01-10 19:48
If no one is working on this, I can fix this issue. @UtkarshMishra12 @legendarykamal @leecalcote

**Comment by leecalcote** [comment] 2023-01-10 19:53
Sounds great. Thank you, @gurpreet-legend

**Closed** 2023-01-31 21:39 UTC
Labels: kind/bug, framework/gatsby, issue/remind, framework/graphql
