### ISSUE TITLE
[UI] Missing Hover effect on clickable cards

### ISSUE THREAD

**Issue by Akshun-01** [layer5io/layer5#5044] opened 2023-10-15 13:39 UTC
### Description

The cards on: https://layer5.io/learn/learning-paths/mastering-service-meshes-for-developers
are clickable but unlike other cards on the website, these do not have the standard glow hover effect.

![image](https://github.com/layer5io/layer5/assets/93793691/912b41f6-c9ee-44ee-8a8f-1b8258f043dc)

### Expected Behavior

These should have the glow effect like on other pages where the cards are clickable.

![image](https://github.com/layer5io/layer5/assets/93793691/9ee498e9-1267-4f1b-ad13-6cfa78cd78c0)

### Environment:
- Host OS: Windows
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by arianxq** [comment] 2023-10-15 14:22
I will solve this issue,

**Comment by arianxq** [comment] 2023-10-15 14:24
I will solve this issue, can you assign it to me?

**Comment by xbelix** [comment] 2023-10-15 17:23
I'm very confident to solve it, assign it to me you will be happy with the results

**Comment by abhijeetgauravm** [comment] 2023-10-15 19:15
Since @arianxq is already assigned to an issue. Let it get assigned to @xbelix!

**Comment by trinayreddy4** [comment] 2023-10-16 14:26
can i get assigned if there is no progress?

**Comment by iampaandey** [comment] 2023-11-04 18:23
is this issue closed ? @abhijeetgauravm

**Comment by abhijeetgauravm** [comment] 2023-11-05 07:07
> is this issue closed ? @abhijeetgauravm

No, @iampaandey, the issue is still open, and there is already an open PR for it. You can help by reviewing the PR, though!

**Comment by roshil1206** [comment] 2023-11-09 04:18
I would like to work on the issue, can you assign it to me.

**Comment by abhijeetgauravm** [comment] 2023-11-10 19:14
@trinayreddy4 @iampaandey any of you would like to work on this?

**Comment by trinayreddy4** [comment] 2023-11-11 02:05
@abhijeetgauravm i would like to take this up

**Comment by trinayreddy4** [comment] 2023-11-11 15:51
@abhijeetgauravm please review the PR and let me know the changes if any.... Hoping to hear it back from you soon.

**Closed** 2023-11-29 23:09 UTC
Labels: kind/bug, hacktoberfest
