### ISSUE TITLE
Outdated Twitter icon

### ISSUE THREAD

**Issue by captain-Akshay** [layer5io/layer5#4961] opened 2023-09-25 02:27 UTC
### Description
The twitter logos used in most of the website of layer5, Old version of twitter logo is used .
example:- https://layer5.io/ (footer)
### Expected Behavior
The logo should be of X which is twitter new logo for better user experience and better design.
### Screenshots
![image](https://github.com/layer5io/layer5/assets/59491379/59c079c4-b87b-497d-a569-9de32efab6b1)

### Environment:
- Host OS:Linux (Ubuntu)
- Browser:Firefox

# I would like to work on this issue if possible. 
---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by VivekBaldha0712** [comment] 2023-09-25 03:05
I would like to work on this

**Comment by captain-Akshay** [comment] 2023-09-25 04:15
> I would like to work on this

It's my First issue let me try this one @VivekBaldha0712 
and i added that i would like to work on that on the issue itself.
Highly appreciated thanks

**Comment by akhilender-bongirwar** [comment] 2023-09-25 04:22
Hey @captain-Akshay , this issue is duplicate of #4631.

**Comment by captain-Akshay** [comment] 2023-09-25 04:31
@akhilender-bongirwar still looks like there this issue is not yet resolved so if @leecalcote assigns i would love to work on fixing it to it's entirety!!

**Comment by Mohith234** [comment] 2023-09-25 09:15
@captain-Akshay One contributor was assigned to that issue, If he is unable to give any update, let's assign it to you. Please comment on that mentioned issue. 

I'm closing this one.

**Closed by Mohith234** 2023-09-25 09:15 UTC
Labels: kind/bug
