### ISSUE TITLE
[Screenshots] Epam Delivery Platform (EDP) Admin Console under "How it Works See It in Action” section

### ISSUE THREAD

**Issue by saurabh100ni** [layer5io/layer5#4829] opened 2023-09-06 09:48 UTC
### Current Behavior
Currently, [every integration](https://layer5.io/cloud-native-management/meshery/integrations/epam-delivery-platform-edp-admin-console) has only two old screenshots of the designer and visualizer in the "How it Works See It in Action” section.

### Desired Behavior
- Add new images and videos from the latest version of the software ([MeshMap](https://layer5.io/cloud-native-management/meshmap))
- Add screenshots for [Epam Delivery Platform (EDP) Admin Console](https://layer5.io/cloud-native-management/meshery/integrations/epam-delivery-platform-edp-admin-console) integration.

### Acceptance Tests
- Ensure your screenshot represents the use of a few specific integrations.
- The screenshot from the Designer mode should contain a valid design, refer to [meshery catalog](https://meshery.io/catalog) to use and view published designs.
- Add both Dark Mode and Light Mode screenshots.
- The screenshot should not be a snippet, take the full screenshot of your browser.
- Use Incognito mode on Chrome browser, to ensure your bookmark bar or any other items are not shown in the screenshot/video.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by ankushbhardwaj408** [comment] 2023-10-02 07:29
Hi @saurabh100ni i would like to work on this. Please assign it to me.

**Comment by abhijeetgauravm** [comment] 2023-10-02 07:33
there u go @ankushbhardwaj408

**Comment by ankushbhardwaj408** [comment] 2023-10-02 09:11
Hi @abhijeetgauravm i am not able to find the epam-delivery integration file in the code. I have checked src/collections/integrations where all other integration files are present but there is no epam-delivery file in it.

**Comment by abhijeetgauravm** [comment] 2023-10-02 09:28
hey @ankushbhardwaj408 Do you have Meshmap access ? Have u set up the project locally? You have too add the new screenshots of the designer and visualizer from the latest version of the software ([MeshMap](https://layer5.io/cloud-native-management/meshmap)).

**Comment by ankushbhardwaj408** [comment] 2023-10-02 09:33
Yes @abhijeetgauravm i have access of meshmap and i have also installed the project locally.Here are the screenshots 
![Screenshot 2023-10-02 143755](https://github.com/layer5io/layer5/assets/93874580/c628bc56-189a-442a-b8b4-80ac6ff3d791)
![Screenshot 2023-10-02 142606](https://github.com/layer5io/layer5/assets/93874580/09298746-d316-4306-be28-1ae67d9413e2)
![Screenshot 2023-10-02 101041](https://github.com/layer5io/layer5/assets/93874580/07e70b81-0d07-4e3a-a863-d3c7279f4a3b)
![Screenshot 2023-10-02 100945](https://github.com/layer5io/layer5/assets/93874580/cf1090be-49b7-43e9-8497-34f94bd28adb)
But the problem is i am not able to find the epam-deliver integration file in the above mentioned folder.

**Comment by abhijeetgauravm** [comment] 2023-10-02 09:45
> Yes @abhijeetgauravm i have access of meshmap and i have also installed the project locally.Here are the screenshots ![Screenshot 2023-10-02 143755](https://user-images.githubusercontent.com/93874580/271934397-c628bc56-189a-442a-b8b4-80ac6ff3d791.png) ![Screenshot 2023-10-02 142606](https://user-images.githubusercontent.com/93874580/271934404-09298746-d316-4306-be28-1ae67d9413e2.png) ![Screenshot 2023-10-02 101041](https://user-images.githubusercontent.com/93874580/271934405-07e70b81-0d07-4e3a-a863-d3c7279f4a3b.png) ![Screenshot 2023-10-02 100945](https://user-images.githubusercontent.com/93874580/271934409-cf1090be-49b7-43e9-8497-34f94bd28adb.png) But the problem is i am not able to find the epam-deliver integration file in the above mentioned folder.

// @sudhanshutech @Chadha93

**Comment by abhijeetgauravm** [comment] 2023-10-02 11:05
> Yes @abhijeetgauravm i have access of meshmap and i have also installed the project locally.Here are the screenshots ![Screenshot 2023-10-02 143755](https://user-images.githubusercontent.com/93874580/271934397-c628bc56-189a-442a-b8b4-80ac6ff3d791.png) ![Screenshot 2023-10-02 142606](https://user-images.githubusercontent.com/93874580/271934404-09298746-d316-4306-be28-1ae67d9413e2.png) ![Screenshot 2023-10-02 101041](https://user-images.githubusercontent.com/93874580/271934405-07e70b81-0d07-4e3a-a863-d3c7279f4a3b.png) ![Screenshot 2023-10-02 100945](https://user-images.githubusercontent.com/93874580/271934409-cf1090be-49b7-43e9-8497-34f94bd28adb.png) But the problem is i am not able to find the epam-deliver integration file in the above mentioned folder.

Let's discuss this Item in today's website call,
Please add it as your agenda if you would:
https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit

**Comment by ankushbhardwaj408** [comment] 2023-10-02 13:13
> > Yes @abhijeetgauravm i have access of meshmap and i have also installed the project locally.Here are the screenshots ![Screenshot 2023-10-02 143755](https://user-images.githubusercontent.com/93874580/271934397-c628bc56-189a-442a-b8b4-80ac6ff3d791.png) ![Screenshot 2023-10-02 142606](https://user-images.githubusercontent.com/93874580/271934404-09298746-d316-4306-be28-1ae67d9413e2.png) ![Screenshot 2023-10-02 101041](https://user-images.githubusercontent.com/93874580/271934405-07e70b81-0d07-4e3a-a863-d3c7279f4a3b.png) ![Screenshot 2023-10-02 100945](https://user-images.githubusercontent.com/93874580/271934409-cf1090be-49b7-43e9-8497-34f94bd28adb.png) But the problem is i am not able to find the epam-deliver integration file in the above mentioned folder.
> 
> Let's discuss this Item in today's website call, Please add it as your agenda if you would: https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit

Hi @abhijeetgauravm I think I missed the meeting because I didn't know the time of the meeting and I just saw your reply

**Comment by abhijeetgauravm** [comment] 2023-10-02 13:17
No sweat @ankushbhardwaj408 Please do Subscribe to the Community Calendar for updates on different meetings: https://layer5.io/community/calendar

**Closed** 2023-12-04 18:38 UTC
Labels: kind/enhancement, help wanted, good first issue, hacktoberfest
