### ISSUE TITLE
Fix the inconsistent Card Size in Contacts Page 

### ISSUE THREAD

**Issue by thisiskaransgit** [layer5io/layer5#4768] opened 2023-08-19 12:31 UTC
### Description
[https://layer5.io/company/contact](https://layer5.io/company/contact)
Card sizes are inconsistent for mobile screens
### Expected Behavior
Card styles need to be updated to be consistent for all mobile screens

Ideally, we need to update the current variables and not introduce new ones

### Screenshots

<img src="https://github.com/layer5io/layer5/assets/92504666/1d4c1288-d9c2-4424-84a3-b7936dbb8b81" width="25%"></img>

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by DarrenDsouza7273** [comment] 2023-08-19 15:31
assigning it to myself ill work on this issue @thisiskaransgit

**Comment by DarrenDsouza7273** [comment] 2023-08-19 15:38
Can u drop the path for the page where the issue is occurring

**Comment by 4ddx** [comment] 2023-08-20 17:42
@DarrenDsouza7273 I think he means that on [page](https://layer5.io/company/contact), when you shift to mobile widths, the contact card, at the bottom goes out of alignment with the other cards.

**Comment by DarrenDsouza7273** [comment] 2023-08-20 17:47
i got what he actually meant i was asking the path where the error is occuring @4ddx

**Comment by thisiskaransgit** [comment] 2023-08-20 17:51
@DarrenDsouza7273, read the issue description please

**Comment by 4ddx** [comment] 2023-08-20 17:53
well the path in the code files should be layer5\src\sections\Company\Contact\index.js 

@DarrenDsouza7273, that's where the components are

**Comment by leecalcote** [comment] 2023-08-22 09:22
@DarrenDsouza7273 how is your progress coming along?

**Comment by jiyanpatil07** [comment] 2023-08-23 19:37
What is the status of this issue?

**Comment by jiyanpatil07** [comment] 2023-08-23 19:38
I would like to work if not assigned

**Comment by DarrenDsouza7273** [comment] 2023-08-24 12:05
> What is the status of this issue?

will be creating a pr today

**Comment by DarrenDsouza7273** [comment] 2023-08-24 12:06
> @DarrenDsouza7273 how is your progress coming along?

Nearly done @leecalcote was busy for the week

**Comment by DarrenDsouza7273** [comment] 2023-08-25 13:19
@jiyanpatil07 please go ahead i have been quite packed for the week

**Comment by jiyanpatil07** [comment] 2023-08-25 17:31
Thank You @DarrenDsouza7273 for the confirmation.

**Comment by DarrenDsouza7273** [comment] 2023-08-25 17:32
sorry for the inconvenience been quite busy lately

**Comment by vobanghia12** [comment] 2023-08-26 04:51
I'd love to work on this one

**Comment by DarrenDsouza7273** [comment] 2023-08-26 04:54
> I'd love to work on this one

It is already assigned to @jiyanpatil07, Meanwhile there are other issues available Please check them out 
Thank you

**Comment by jiyanpatil07** [comment] 2023-08-26 17:56
@vobanghia12 I'm working on the issue,Thank You.

**Comment by Ghat0tkach** [comment] 2023-08-27 19:03
hey @jiyanpatil07 
let's discuss about your progress on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)
https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Comment by jiyanpatil07** [comment] 2023-08-27 20:10
@Ghat0tkach Hello,
I have added the agenda in docs, will connect in meeting.
Also I have created a PR for the Issue please have a look.
Thank You.

**Comment by ankushbhardwaj408** [comment] 2023-11-06 14:03
I would like to work on this.

**Closed** 2023-11-29 23:06 UTC
Labels: kind/bug, help wanted, good first issue, hacktoberfest
