### ISSUE TITLE
layer5 menu view  not showing all options

### ISSUE THREAD

**Issue by gunjanmimo** [layer5io/layer5#340] opened 2020-02-20 07:01 UTC
when we use the menu button in small browser window, it's not showing the 
![Screenshot from 2020-02-20 12-27-27](https://user-images.githubusercontent.com/46948185/74908711-9e2ed000-53dc-11ea-984d-a448acdac9c4.png)
list of options

**Comment by leecalcote** [comment] 2020-02-20 14:01
Duplicate of #339?

**Comment by gunjanmimo** [comment] 2020-02-21 16:00
oh, I did not notice. I am closing this pr

**Closed** 2020-03-05 04:58 UTC
Labels: bug
