### ISSUE TITLE
[Visual Design] MeshMap hero: 3D logo

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#4295] opened 2023-05-26 04:51 UTC
### Current Behavior
The [top-level MeshMap page](https://layer5.io/cloud-native-management/meshmap) has a large, flat logo visible in the right side of the hero.

### Desired Behavior
A large, 3D version of the same logo is displayed instead.

### Implementation
1. Generate a 3D rendering for prominent placement on this page.
2. Consider how to ensure that this design is responsive.

### Acceptance Tests
1. Design must relative small in footprint so as to not affect page speed.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by leecalcote** [comment] 2023-05-26 04:51
@vishyfishy7, this one is for you...

**Comment by VishyFishy7** [comment] 2023-05-26 08:08
@leecalcote On it.

**Comment by DarrenDsouza7273** [comment] 2023-05-28 02:01
@leecalcote can i also share my thoughts on it?

**Comment by leecalcote** [comment] 2023-05-28 05:54
@DarrenDsouza7273, yes, please do.

**Comment by VishyFishy7** [comment] 2023-05-30 15:30
![Meshmap](https://github.com/layer5io/layer5/assets/134532008/a7a09d4c-c8cb-4cb5-9c70-5ee33c7cb164)
Here is the 3d icon with preview on Meshmap page.

**Comment by DarrenDsouza7273** [comment] 2023-06-01 11:33
@leecalcote check this out

**Comment by leecalcote** [comment] 2023-06-01 20:15
Oooh, nice. Let's ensure that the angle of the Meshery icon and the angle of the location icon are both being held constant as perspective is applied.

**Comment by Savio629** [comment] 2023-06-26 11:24
@VishyFishy7 Any updates on the required changes?

**Comment by Savio629** [comment] 2023-07-04 16:15
@VishyFishy7 Can you share the 3d model/code used for it?

**Comment by VishyFishy7** [comment] 2023-07-05 09:45
![3](https://github.com/layer5io/layer5/assets/134532008/95edc39a-5bec-460f-a3f3-6ddbeed3da2f)
@Savio629

**Comment by Yana-Gupta** [comment] 2023-07-14 16:53
@leecalcote I would like to volunteer if no one is working on this issue.

**Comment by DarrenDsouza7273** [comment] 2023-07-14 16:54
> @leecalcote I would like to volunteer if no one is working on this issue. 

hi @Yana-Gupta The issue is already resolved by @VishyFishy7. If you could mention anything to make it better please do

**Comment by Yana-Gupta** [comment] 2023-07-15 06:13
> > @leecalcote I would like to volunteer if no one is working on this issue.
> 
> hi @Yana-Gupta The issue is already resolved by @VishyFishy7. If you could mention anything to make it better please do

hi @DarrenDsouza7273, okay no worries

**Comment by leecalcote** [comment] 2023-07-16 06:57
@VishyFishy7 put in some great work. His focus has shifted elsewhere, though, and so @Yana-Gupta, it would be great if you can give this a go.

**Comment by Yana-Gupta** [comment] 2023-07-16 07:09
> @VishyFishy7 put in some great work. His focus has shifted elsewhere, though, and so @Yana-Gupta, it would be great if you can give this a go.

okay sir

**Closed** 2023-07-29 14:20 UTC
Labels: kind/enhancement, type/ux, type/visual design
