### ISSUE TITLE
add Meshery Catalog card to projects grid and change card sizes according to their significance

### ISSUE THREAD

**Issue by avikt18** [layer5io/layer5#3653] opened 2023-01-20 12:46 UTC
#### Current Behavior
The Meshery Catalog card is missing from the projects grid on [this](https://layer5.io/projects) webpage.

#### Desired Behavior
Add meshery catalog card and change the card sizes to according to their importance.

#### Mockups
Mockup for the new projects grid: 
![image](https://user-images.githubusercontent.com/56340999/213697941-721539af-1de4-44d4-bcc0-24c53663cd3c.png)
 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by SumeetMaurya** [comment] 2023-01-22 08:32
can you please assign this issue to me

**Comment by tinniaru3005** [comment] 2023-01-25 19:47
Hey, @SumeetMaurya welcome to the community. Hey, @avikt18 can you please confirm whether the design is finalized? Then the issue can be assigned to @SumeetMaurya.

**Comment by avikt18** [comment] 2023-01-26 12:31
@leecalcote the issue is valid right?

**Comment by Bidhu1024** [comment] 2023-01-31 15:49
Please assign the issue to me @tinniaru3005 .

**Comment by tinniaru3005** [comment] 2023-01-31 16:00
Hey, @Bidhu1024 the design changes are not yet confirmed. And even if it is confirmed it will be assigned in the order of who asked first. You can find another issue for you which is not assigned to anyone and be the first one to ask for it. Also, you are welcome to create new issues to report ant new bugs as well.

**Comment by Bidhu1024** [comment] 2023-01-31 16:01
Cool. Thanks

**Comment by tinniaru3005** [comment] 2023-01-31 16:02
> Cool. Thanks

Have a look at the [repository-overview](https://layer5.io/community/handbook/repository-overview) to explore other projects as well

**Comment by money8203** [comment] 2023-03-19 09:18
@tinniaru3005 is this issue still in action ?

**Comment by 8rxn** [comment] 2023-05-13 13:54
Hey,
If the issue is still relevant, I would like to work on the issue.

**Comment by Savio629** [comment] 2023-06-19 18:36
@vishalvivekm Are we still planning on adding meshery catalog to the projects page?

**Comment by vishalvivekm** [comment] 2023-06-19 18:38
> @vishalvivekm Are we still planning on adding meshery catalog to the projects page?

We did @Savio629 check it out : https://layer5.io/projects
Thanks to @goldfishdolphin

**Comment by Savio629** [comment] 2023-06-19 19:57
Oops missed out the changes🙂
Should we close this issue then?

**Comment by leecalcote** [comment] 2023-06-19 20:19
@Savio629 if we have the Playground represented in addition to what is diagrammed in the description, yes, I think so.

**Closed** 2023-07-28 19:32 UTC
Labels: kind/enhancement, issue/remind
