### ISSUE TITLE
Link for the case study banner is broken

### ISSUE THREAD

**Issue by vrinda-mahajan** [layer5io/layer5#4545] opened 2023-07-14 20:01 UTC
### Description
The link for the case study banner on the home page is broken, as it is still pointing to https://layer5.io/resources/cloud-native/hpes-adoption-of-meshery-and-meshmap

### Expected Behavior
It should point to https://layer5.io/resources/case-study/hpes-adoption-of-meshery-and-meshmap

### Screenshots

https://github.com/layer5io/layer5/assets/72399705/32bcb86c-36e0-459f-b467-d386d6866894

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by ayushsinha25** [comment] 2023-07-14 20:35
You may assign it to me @vrinda-mahajan

**Comment by hirentimbadiya** [comment] 2023-07-15 04:18
assigning FCFS wise, @vrinda-mahajan you can fix this issue.

**Comment by leecalcote** [comment] 2023-07-16 06:10
@Shivam-AfA?

**Comment by leecalcote** [comment] 2023-07-16 06:12
Caused by this PR https://github.com/layer5io/layer5/pull/4544

**Comment by leecalcote** [comment] 2023-07-16 06:13
In addition to the fix in this reference, we need to ensure that a redirect is in place for the old location.

**Comment by leecalcote** [comment] 2023-07-16 06:14
We need this fixed pronto. @Shivam-AfA

**Closed** 2023-07-16 06:40 UTC
Labels: kind/bug, priority/urgent

**Comment by leecalcote** [comment] 2023-07-16 06:49
Thank you, @vrinda-mahajan! 👏
