### ISSUE TITLE
Fix Inconsistent newsletter Position 

### ISSUE THREAD

**Issue by thisiskaransgit** [layer5io/layer5#4750] opened 2023-08-17 12:54 UTC
### Current Behavior
The newsletter component is overlapping for screen widths of ~723px
<img src ="https://github.com/layer5io/layer5/assets/92504666/1a17b28f-45cc-490d-89df-58b2215adadd" width="50%"></img>

### Desired Behavior
No overlapping of elements
### Implementation
Update the width specific styles to be consistent  
### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by malaviya-parth** [comment] 2023-08-17 13:22
I would like to work on it

**Comment by kituuu** [comment] 2023-08-17 13:30
Can I work on it?

**Comment by JaeAeich** [comment] 2023-08-17 13:44
I'd love to work on this one :)

**Comment by thisiskaransgit** [comment] 2023-08-17 14:51
As discussed in the meeting @JaeAeich,   go ahead and fix it :rocket:

**Comment by dibyendu02** [comment] 2023-08-18 06:38
I want to work on this issue

**Comment by Vivek7038** [comment] 2023-08-18 14:52
hey on which brwoser and screen ratio you are getting this inconsistent , as i am unable to reproduce this bug

> ### Current Behavior
> ![](https://user-images.githubusercontent.com/92504666/261312551-1a17b28f-45cc-490d-89df-58b2215adadd.png)
> 
> ### Desired Behavior
> ### Screenshots / Mockups
> ### Implementation
> ### Acceptance Tests
> <img alt="" width="24px" src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg">
> 
> ## Contributor Resources and [Handbook](https://layer5.io/community/handbook)
> The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
> 
> * 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
> * 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
> * 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).
> 
> <img alt="" height="22px" src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp">Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

hey on which brwoser and screen ratio you are getting this inconsistent , as i am unable to reproduce this bug

**Comment by JaeAeich** [comment] 2023-08-18 16:32
@Vivek7038 
- aspect - 724x850

**Comment by JaeAeich** [comment] 2023-08-20 09:54
Did anyone find the issue here? Most of the CSS properties have `!important` on them in the media query, so its very hard to pin point where the error is coming from.

**Comment by Ghat0tkach** [comment] 2023-08-27 19:03
hey @dibyendu02 
let's discuss about your progress on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)
https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Comment by dibyendu02** [comment] 2023-08-27 19:12
hey @Ghat0tkach I was unaware that I was assigned, didn't get any notification.
let's connect tommorow over this

**Comment by prabhjeevnijjar** [comment] 2024-01-05 08:10
My PR #5214 . fixes this issue.

**Comment by prabhjeevnijjar** [comment] 2024-01-05 09:47
> My PR #5214 . fixes this issue.

@saurabh100ni

**Comment by saurabh100ni** [comment] 2024-01-20 09:22
PR [#5214](https://github.com/layer5io/layer5/pull/5214) by @prabhjeevnijjar has fixed this issue and is good to go, so I am closing this issue.

**Closed by saurabh100ni** 2024-01-20 09:22 UTC
Labels: kind/enhancement, good first issue
