### ISSUE TITLE
Text Overflow on all internship pages and are not responsive

### ISSUE THREAD

**Issue by vrushabhgawas14** [layer5io/layer5#6038] opened 2024-10-28 16:22 UTC
### Description
- `Apply By` and `Layers` text are merging.
- On Zoom `Stipend` text goes out of the box.
issue at : https://layer5.io/careers/digital-marketing-internship

### Screenshots
1)
![Screenshot (258)](https://github.com/user-attachments/assets/8ab34faa-4a20-4066-acbf-3ffa92d14c89)
2)
![Screenshot (259)](https://github.com/user-attachments/assets/b16add04-8b9b-48f0-bf53-c3d17f684c9a)

### Expected Behavior
Need to work on Css for above issues.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by vrushabhgawas14** [comment] 2024-10-28 16:23
I want to work on these issues.

**Comment by hargunkaur286** [comment] 2024-11-01 11:37
Please go ahead @vrushabhgawas14 🚀

**Comment by vishalvivekm** [comment] 2024-11-03 15:39
@vrushabhgawas14 @hargunkaur286 

is this a Duplicate of #5997 ? // @upsaurav12

**Comment by upsaurav12** [comment] 2024-11-03 15:42
This was from the digital-marketing-intership page .
I dont think it is duplicate

**Comment by vishalvivekm** [comment] 2024-11-03 15:45
> This was from the digital-marketing-intership page . I dont think it is duplicate

:heavy_check_mark: 
Thank you very much for confirming @upsaurav12

**Comment by vrushabhgawas14** [comment] 2024-11-03 15:59
> @vrushabhgawas14 @hargunkaur286
> 
> is this a Duplicate of #5997 ? // @upsaurav12

Both are different, This is for all internship pages.
And that #5997 maybe for careers pages.

**Closed** 2024-12-09 20:31 UTC
Labels: kind/bug
