### ISSUE TITLE
[Integrations] Terraform logo is skewed 

### ISSUE THREAD

**Issue by eeshaanSA** [layer5io/layer5#3500] opened 2022-12-05 05:22 UTC
#### Description

![image](https://user-images.githubusercontent.com/100678386/205555321-1afae2d4-6648-4b27-8734-7205fe19edde.png)

#### Expected Behavior

![image](https://user-images.githubusercontent.com/100678386/205555457-7b01a4df-aaac-4e95-b922-92e920f42bed.png)

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Lonecloud7** [comment] 2022-12-05 09:24
Can I get a link to the page with this issue?

**Comment by GaganpreetKaurKalsi** [comment] 2022-12-05 13:49
> Can I get a link to the page with this issue?

Sure! Here it is, [link](https://layer5.io/cloud-native-management/meshery/integrations/). Terraform is the 4th last among the integrations.

**Comment by tinniaru3005** [comment] 2022-12-06 11:44
Hey @GaganpreetKaurKalsi, I can solve it. Can you please assign it to me?

**Comment by eeshaanSA** [comment] 2022-12-06 11:49
I am not sure if @Lonecloud7 is working on it already. @Lonecloud7 are you?

**Comment by Lonecloud7** [comment] 2022-12-06 12:27
> I am not sure if @Lonecloud7 is working on it already. @Lonecloud7 are you? 

No, I'm currently not working on it

**Comment by tinniaru3005** [comment] 2022-12-06 20:09
@leecalcote I guess we can close this issue also

**Comment by eeshaanSA** [comment] 2022-12-06 20:11
@tinniaru3005 thanks for the confirmation.

**Comment by leecalcote** [comment] 2022-12-06 20:15
Oh, my goodness! I just looked back at the screenshot above. 😵‍💫 Yes, it _is_ skewed. 😆 

Adjusting padding isn't ideal, though. Please confirm that only height or only width is specify for the logos. The aspect ratio will be retained in this situation. Changing padding like proposed will affect all logos.

**Comment by eeshaanSA** [comment] 2022-12-06 20:18
@leecalcote , right now on the site it isn't. It looks just fine. 😵‍💫😵‍💫

![image](https://user-images.githubusercontent.com/100678386/206014050-b598c401-2356-437d-b121-9646f4908df1.jpeg)

**Comment by leecalcote** [comment] 2022-12-06 20:19
Uh-oh. Is a media query causing us confusion?

**Comment by eeshaanSA** [comment] 2022-12-06 20:21
I doubt, looks fine for mobile, tablet, desktop 😵‍💫

**Comment by eeshaanSA** [comment] 2022-12-06 20:23
Did someone maybe fix this in another PR?

**Comment by GaganpreetKaurKalsi** [comment] 2022-12-06 21:36
I can  👀  the skewed terraform logo.
OS: MacOS
Browser: Chrome

**Comment by GaganpreetKaurKalsi** [comment] 2022-12-06 21:48
All integration images are at height 100%. Removing `height: 100%` from `img` tag solves the issue.

**Comment by eeshaanSA** [comment] 2022-12-07 04:37
> Ha! You found the magic combination. Wow, isn't that odd to think how / why OS matters?

Heard of browser specific issues, but this is OS specific. How?

**Comment by eeshaanSA** [comment] 2022-12-07 04:39
> All integration images are at height 100%. Removing `height: 100%` from `img` tag solves the issue.

Yup, that will solve the problem for all integration icons, because there can be different logos skewed for different OS/browser combos.

**Comment by leecalcote** [comment] 2022-12-07 04:48
@tinniaru3005 ^^

**Comment by leecalcote** [comment] 2022-12-07 04:49
Apparently, size matters. 


🤭

**Comment by eeshaanSA** [comment] 2022-12-07 05:56
> Apparently, size matters. 
> 
> 
> 
> 
> 
> 🤭

😳

**Comment by tinniaru3005** [comment] 2022-12-08 10:33
> @tinniaru3005 ^^

Ya @leecalcote I looking into it.

**Comment by tinniaru3005** [comment] 2022-12-08 13:30
Hey @leecalcote the logo looks fine now. Is the issue fixed. But there is another issue. If I am hovering on the logo image then the whole name is not showing if the name is a bit long. Example: KubeEdge, Terraform some letters are getting cut out from both the ends.

**Comment by Sajiyah-Salat** [comment] 2023-01-02 08:19
Hey @tinniaru3005 I don't think the issue is fixed as I can see skewed Terraform logo.
OS: Ubuntu
browser: Firefox

**Comment by Sajiyah-Salat** [comment] 2023-01-02 08:19
Hey @tinniaru3005 I don't think the issue is fixed as I can see skewed Terraform logo.
OS: Ubuntu
browser: Firefox

**Comment by GaganpreetKaurKalsi** [comment] 2023-01-02 20:27
Closing this issue. Fixed in #3582

**Closed by GaganpreetKaurKalsi** 2023-01-02 20:27 UTC
Labels: kind/bug, good first issue, language/css
