### ISSUE TITLE
[UI] Incorrect Formatting of the table header on multiples instances

### ISSUE THREAD

**Issue by saaagarsingh** [layer5io/layer5#4508] opened 2023-07-07 18:40 UTC
### Description
Li(list) tags are not covering the whole area which makes the UI bad due to blank spaces.
https://layer5.io/service-mesh-landscape
https://layer5.io/projects/service-mesh-interface-conformance

### Expected Behavior
Li tags should span and cover whole table header wihtout leaving blank space. Bluw space should not be visible

Screenshots for Reference:

![servieMaceLandscape1](https://github.com/layer5io/layer5/assets/85694019/a070d29f-8f06-44bc-9944-d28235d82c7c)

![servieMaceLandscape2](https://github.com/layer5io/layer5/assets/85694019/a7325947-3ab0-4209-8e6c-2dc632f39285)

### Environment:
- Host OS: Windows10
- Browser:Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by harshit-senpai** [comment] 2023-07-07 19:27
hey i want to work on it

**Comment by iampaandey** [comment] 2023-07-08 17:31
Please assing this to me @leecalcote

**Comment by mayurjadhav2002** [comment] 2023-07-11 06:41
Hi! After carefully reading the issue you shared @saaagarsingh and reviewing the source code, it appears to me that this bug is caused by an incorrect value for the **justify-content** property. To fix this, the parent element should be set to "**flex**" and the child element's justify property needs to be changed. I am interested in working on this issue. If possible, could you please assign this issue to me, @leecalcote ?

**Comment by Harsh-2004** [comment] 2023-07-12 18:27
Can I work on this too

**Comment by leecalcote** [comment] 2023-07-12 18:29
Folks, I (and other maintainers here) very, very, very much appreciate your engagement. This issue just isn't an area of open need / doesn't meet the bar of criticality to spend time on and potentially introduce a bug into. There are many other open areas of need, though: 164 open, help wanted issues, in fact - https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+

**Closed by leecalcote** 2023-07-12 18:29 UTC
Labels: kind/bug
