### ISSUE TITLE
[bug] in small device whole header is clickable as logo

### ISSUE THREAD

**Issue by singhvivek7** [layer5io/layer5#5352] opened 2024-01-27 01:38 UTC
### Description
In small device view when we have hamburger, logo is covering whole width and clickable.

### Expected Behavior
Only logo should be clickable 

### Screenshots
https://github.com/layer5io/layer5/assets/153614040/4e580eda-fc07-44e6-af97-dcdf3e57b85b

### Environment:
- Host OS: Android
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by vivekartist7** [comment] 2024-01-27 01:39
I wanted to work on it

**Comment by savitakatwe** [comment] 2024-02-01 11:49
I would like to work on this task.Assign to me please.

**Comment by Ashparshp** [comment] 2024-02-01 13:56
@saurabh100ni please review the small device view issue start for width less than 1101.

**Comment by saurabh100ni** [comment] 2024-02-01 17:31
Thanks for the heads-up @Ashparshp, The issue persists.
@vivekartist7 would you still like to work on it? If not, then we can get this assigned to @savitakatwe.

**Comment by saurabh100ni** [comment] 2024-02-01 17:44
Great 😃 @vivekartist7

**Comment by leecalcote** [comment] 2024-02-07 23:18
I'm not able to reproduce this issue. Is it valid, @iArchitSharma?

**Comment by Ashparshp** [comment] 2024-02-08 03:53
@leecalcote issue start for width less than 1101.

**Comment by Ashparshp** [comment] 2024-02-08 03:58
Uploading screenrecorder-2024-02-08-09-20-56-218_Oc36IGgK.mp4…

**Comment by Ashparshp** [comment] 2024-02-11 11:24
@vivekartist7 It lookss like what you're describing is more of a design consideration rather than a technical issue. While the logo covering the whole width and being clickable might not align with typical expectations, it can still serve as a means for users to navigate to the main page. However, to enhance user experience and provide clearer feedback, adding a hover effect to indicate clickability is a great suggestion. This would help users understand that they can interact with the logo to navigate to the main page, addressing any potential confusion. Overall, incorporating this hover effect can improve usability and make the navigation experience more intuitive for users.

@leecalcote @saurabh100ni, what are your thoughts on this approach?

**Comment by vivekartist7** [comment] 2024-02-11 13:48
@Ashparshp sure, we can scale a bit while hovering on logo.

**Closed** 2024-03-18 03:34 UTC
Labels: kind/bug
