### ISSUE TITLE
In devices width<1100 links of the verticle navbar are not behaving as expected

### ISSUE THREAD

**Issue by Manishch27** [layer5io/layer5#5389] opened 2024-02-11 21:30 UTC
### Description
In small devices width<1100px in the verticle navBar when we click on any link it covers the whole list and a blue layer is there on the whole content.

### Expected Behavior
Only the content should be clickable and also there should not be any blue layer on the content.

### Screenshots

https://github.com/layer5io/layer5/assets/98028450/ae6b6ea1-0da9-46e7-a271-0e037ab6ea8f

### Environment:
- Host OS: Android
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Manishch27** [comment] 2024-02-11 21:32
I would like to work on this issue.

**Comment by Ashparshp** [comment] 2024-02-12 14:50
Thanks for flagging. It might be a design choice rather than a bug. Appreciate your feedback, @saurabh100ni. Right?

**Comment by myselfprincee** [comment] 2024-02-13 05:07
I feel it is not a bug but when ever you build a website and use it in your phone, it is a native style The Browser provides there's a css class to remove it

A single line and it will be fixed.

**Comment by Ashparshp** [comment] 2024-02-13 05:10
@myselfprincee But it provides better feedback to the user whenever get clicked..

**Comment by myselfprincee** [comment] 2024-02-13 05:38
> @myselfprincee But it provides better feedback to the user whenever get clicked.. 

Yes for sure

**Comment by Ashparshp** [comment] 2024-02-13 05:47
@saurabh100ni, it seems this issue may not be valid. Can we close it?

**Comment by vishalvivekm** [comment] 2024-02-22 17:18
> @Manishch27, thanks for raising this concern. I fail to see where there's a blue layer. Could you help me understand the issue that you're describing a bit more? At the moment, it's not clear that there's sufficient evidence to warrant action here (that the behavior shown in the screen recording is a bug).

@Manishch27 thoughts??

**Comment by Manishch27** [comment] 2024-02-23 19:47
I agree with @myselfprincee and @Ashparshp it's not a bug it's a design choice and I apologize for the wrong label, but I don't find any label related to the design. When we open the layer5 website on the phone and click on any of the navigation links from the verticle navBar a blue layer appears on the top of the clicked link for a faction of seconds, it's a default styling provided by the browser for the links, but we can correct it with the help of CSS for the better user interface. @leecalcote attachment helps you to understand the issue better with current behavior and expected behavior.

https://github.com/layer5io/layer5/assets/98028450/d461e029-1a76-4eed-878f-a2bc1050f756

**Comment by Ashparshp** [comment] 2024-05-14 17:39
If this isn't considered an issue, shall we close it? @vishalvivekm @Manishch27

**Comment by myselfprincee** [comment] 2024-05-14 17:42
I think we should

**Closed** 2024-05-14 17:45 UTC
Labels: kind/bug
