### ISSUE TITLE
[UX] Icons are hidden on the landing page

### ISSUE THREAD

**Issue by legendarykamal** [layer5io/layer5#3072] opened 2022-08-12 18:15 UTC
#### Current Behavior

![image](https://user-images.githubusercontent.com/95926324/184419186-52610618-03b7-442f-9695-00b64a2e5e4e.png)
Many Icons are hidden on the landing page.
#### Desired Behavior

As seen these icons should be visible to make the best of UX , 
The idea I would suggest is to get these icons rolling from left to right so that all are visible and in less space.
#### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by legendarykamal** [comment] 2022-08-12 18:17
Would someone like to implement this cool auto roll slider with me?

**Comment by legendarykamal** [comment] 2022-08-12 18:19
@leecalcote @Chadha93 @debo19 can we implement this cool auto roll slider on the layer5 website?

**Comment by leecalcote** [comment] 2022-08-12 18:22
Great idea. There are a number of other items that are in need of help, though, instead. This section and the cut-off is by design.

Here's what we do need: new sections on the home page highlighting Meshery and MeshMap features. Feel free to engage with any of the UXers that have recently joined to collaborate on this effort (and you might open an issue, too).

**Comment by legendarykamal** [comment] 2022-08-12 18:25
oh okk design part , ya I will open an issue for this :+1:

**Comment by debo19** [comment] 2022-08-12 20:09
Closing this issue.

**Closed by debo19** 2022-08-12 20:09 UTC
Labels: kind/enhancement, issue/wontfix
