### ISSUE TITLE
[UI] Remove whitespace in cards

### ISSUE THREAD

**Issue by Chadha93** [layer5io/layer5#3853] opened 2023-03-01 19:43 UTC
**Current Behavior**
![image](https://user-images.githubusercontent.com/65453826/222247030-c2016135-57fa-4dbb-8dcc-43717967ab08.png)

**Desired Behavior**
Remove the extra white space between the logo and the text in the cards.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by scorcism** [comment] 2023-03-02 01:20
Hey, can i work on this ?

**Comment by sambhavgupta0705** [comment] 2023-03-02 06:51
Hi @Chadha93 I would like to work on this issue and get started as a contributor in layer5 org.

**Comment by melsonic** [comment] 2023-03-04 13:45
Hey, @scorcism are you still working on it?

**Comment by scorcism** [comment] 2023-03-04 15:00
@leecalcote Sorry to bother you, I got my test so won't be able to spend time on this.

**Comment by scorcism** [comment] 2023-03-04 15:01
@melsonic no buddy

**Comment by melsonic** [comment] 2023-03-04 15:57
Thanks @scorcism . 
I want to work on the this one. Can anyone assign me please?

**Comment by leecalcote** [comment] 2023-03-04 16:05
@scorcism, thanks much for sending word.

@melsonic, batter up.

**Comment by Anishsme** [comment] 2023-03-05 14:21
Hey is this issue still open ?

**Comment by melsonic** [comment] 2023-03-05 14:35
I am working on it.

**Comment by ankushbhardwaj408** [comment] 2023-04-02 06:59
Hii @leecalcote is this issue still open ?

**Comment by leecalcote** [comment] 2023-04-02 17:22
@ankushbhardwaj408 good question. I believe that @melsonic just opened up a PR with a potential fix. It'd be great for you to offer review on of that PR - https://github.com/layer5io/layer5/pull/3905

**Comment by ankushbhardwaj408** [comment] 2023-04-03 00:57
Sure i will @leecalcote

**Comment by HemanthPaila** [comment] 2023-04-03 02:57
Hey, @leecalcote and @Chadha93 is this issue still open?
 - If opened could you please assign it to me?

**Comment by avikt18** [comment] 2023-04-10 14:26
@HemanthPaila The issue is being worked on by @melsonic. Meanwhile, you can check out other issues 🙂.

**Comment by DarrenDsouza7273** [comment] 2023-05-31 05:55
@melsonic can u update regarding your progress

**Comment by melsonic** [comment] 2023-05-31 06:03
> @melsonic can u update regarding your progress
> 

I have done the coding part, now waiting for a response from the maintainers.

**Comment by DarrenDsouza7273** [comment] 2023-05-31 06:14
> > @melsonic can u update regarding your progress
> 
> I have done the coding part, now waiting for a response from the maintainers.

thankss

**Comment by AjaysingRajput** [comment] 2023-06-12 16:39
i want work on this issue can you asign me.

**Comment by HetviSoni** [comment] 2023-07-13 11:01
Hey @Chadha93 is this a valid issue? As the current website is not having this issue.

**Comment by HetviSoni** [comment] 2023-07-15 04:51
Yes @Savio629 actually the issue description is about the white space between the logo and text in the card. But in the current website this is not the case. So I am confused😅
<img width="850" alt="image" src="https://github.com/layer5io/layer5/assets/76479104/b56134a1-9380-49ae-be9d-8cb85517ee7c">

**Comment by Savio629** [comment] 2023-07-15 07:13
We can discuss this issue in weekly meeting.

**Closed** 2023-09-30 15:06 UTC
Labels: help wanted, good first issue, component/ui
